### ISSUE TITLE
Updated (Revision) date suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#102]
At the minute the "Published" date is shown but it would be useful to have an optional "Updated" (Revised?) date as well on the download sidebar.

**Comment by amdrew** [comment]
@davidsherlock I'm not a fan of including an updated/revised date for the simple reason that it would need to be the date WordPress assigns when the download was last saved. 

This leads to the problem of the download looking like it's always being updated, even if you went in and changed a typo. This can cause some confusion between something like a changelog, where the last version could be 1 month prior, but the revised/updated date shows the current day.

IMO this is best suited to a metabox on the download itself, where the admin can then set the last updated/revised date to when they actually updated it. Something like this:

<img width="313" alt="screenshot 2017-09-19 21 11 58" src="https://user-images.githubusercontent.com/52581/30584857-321a8a96-9d7f-11e7-835e-f5ad1edaeabc.png">

Keen to hear your thoughts if you disagree.

**Comment by davidsherlock** [comment]
Was actually thinking that myself regarding typos and alike. You should (if you have time)’make the meta plugin available on GitHub and ideally relatively extendable so custom fields can be added.

I had an idea a while back to make a plugin for EDD that allows you to build a “meta” section using custom fields and alike, so it can cater for any type of business.

You sent me the meta plugin before so I’ll use that for now!

**Comment by amdrew** [comment]
It's very easy to extend using the included hooks etc. I also had plans to allow you to select the type of download from a dropdown and it would give you fields based on the type of download. However, it will most likely only ever be for internal use. We do have a plugin in the works which is a better alternative for this type of thing, no ETA though.
