### ISSUE TITLE
Account (customer dashboard) integration and page template suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#106]
I am actually in the processing of adding this to my own theme, but felt it was worth suggesting for Themedd as well.

It would be useful to have a "Customer Dashboard" page template that featured a tab interface exactly like RCP and AWP use. The tabs would be dynamically added based on the plugins installed (and active), for example a "Subscriptions", "Profile", "Licenses", "Downloads", etc. This would make it integrate seamlessly with EDD and the various extensions.

Similarly, much like the "Cart" icon a new profile icon could be added that when clicked would redirect to the account page. When not logged in it would show the login page when clicked, and the account page when logged in. Adding a logout option would also be useful.

**Comment by rubengc** [comment]
Tabs on this page could be easily done with a plugin (EDD Account Tabs) or you can place all shortcodes inside the required html to build the page like you want (for example adding purchase_history and download_history in the same tab)

But something interesting is add a menu location (similar to primary/secondary/mobile menus) named user menu with a dynamic functionallity to show some items when user is logged in

The problem of this menu location is the need to add another menu for guests users (to solved the need If anyone want to have on separated pages the login and register form)

At this moment I solved this need with a menu permission plugin that allows show menu items based on user role or if is logged in or not

**Comment by amdrew** [comment]
Themedd _used_ to have an account page template but I removed it: https://github.com/easydigitaldownloads/themedd/commit/6c6a5d79bc7b56ca2c989ab3a37d40f23e76420c

I believe EDD core should have an account built-in like WooCommerce. Other plugins such as Software Licensing, AffiliateWP etc can hook in and add their own sections where needed.

**Comment by pippinsplugins** [comment]
I agree with @amdrew. See https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5398

**Comment by amdrew** [comment]
Thanks for the issue link @pippinsplugins!

Closing.
