### ISSUE TITLE
Additional developer hooks required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#109]
@amdrew, want to suggest some more hooks throughout the theme for child-theme developers. This is mainly to reduce template duplication and keep things cleaner.

`sidebar-single-vendor.php`

- A hook just above and one below `<section class="widget downloadAuthor">`.
- A hook just above and one below the closing `</section>`

`sidebar.php`

-  `a themedd_primary_sidebar_end` after the dynamic side bar.

Ideally it would be possible to extend the widgets as well, but I'm not sure how feasible that is or if they can be overridden via a child theme? For example adding the ability to add additional settings and html output, etc.

**Comment by amdrew** [comment]
@davidsherlock 👍 Those sound good

**Comment by davidsherlock** [comment]
A few more additions:

`sidebar-download.php`

- One just after the opening `<section class="widget downloadAuthor">`
- One just before the end '</section>'

`footer.php`

One just before the closing `</div>` and after the `</footer>`.

**Comment by amdrew** [comment]
@davidsherlock 

**sidebar-single-vendor.php**
themedd_edd_fes_sidebar_single_vendor_end
themedd_edd_fes_sidebar_single_vendor_start

**sidebar.php**
themedd_primary_sidebar_end

For https://github.com/easydigitaldownloads/themedd/issues/109#issuecomment-326831002, can you elaborate on what you need to add in those locations on sidebar-download.php so I can better understand? One is above the avatar and the other is at the bottom, outside of the `<ul>` that's already there.

Also, the same for the footer. What would you need to place outside of the `footer` element? Could it not be loaded on `themedd_footer` with a higher priority?

**Comment by davidsherlock** [comment]
@amdrew, to add new data to the author widget area (and similarly download details). To keep everything cohesive it would be better to be within the section tags.

Footer one can be omitted.

**Comment by amdrew** [comment]
@davidsherlock 👍 Do you think it would make more sense to add a hook just before the closing `</ul>`, rather than before the `</section>` on `sidebar-download.php`? I would imagine that if you were adding more data, you'd want it within the same unordered list.

**Comment by davidsherlock** [comment]
Definitely one before and after the `<ul></ul>` tags. Good shout!

**Comment by amdrew** [comment]
Would you really need a hook _after_ the `</ul>` if one was included before? I'd imagine that the data added is related to the rest of the options so should go in the same list.

**Comment by davidsherlock** [comment]
Sorry, I miswrote that! What I mean is one after the first `<ul>` and one before the last `</ul>`.

**Comment by amdrew** [comment]
@davidsherlock

themedd_edd_sidebar_download_author_list_start
themedd_edd_sidebar_download_author_list_end

themedd_edd_sidebar_download_details_list_start
themedd_edd_sidebar_download_details_list_end

Hooks are also available on the widgets

**Comment by amdrew** [comment]
This seems complete, closing!
