### ISSUE TITLE
Alternate checkout layout

### ISSUE THREAD

**Issue by sumobi** [easydigitaldownloads/themedd#11]
I'm thinking of including an alternate checkout layout like we have for AffiliateWP and Restrict Content Pro. This would remove the header navigation, footer widgets, center the site title, sidebars, make the checkout table slimmer etc.

Rather than including a page template I think a customiser checkbox option makes much more sense. This would appears in a new section called "Easy Digital Downloads".

A few notes:

- Page templates imply you would use it more than once, for example, to make a page full-width. There's only 1 checkout page, as set by EDD, and we know which page ID it is.
- Including a page template means it needs to be unset if EDD is not active, leading to unnecessary code. While it's a theme for EDD, some may use it without
- The actual page template would look more or less like the normal page.php anyway. So it's confusing to say "here's a page template you can copy over to your child theme" but then find out there's no actual navigation in it, or anything related to what it actually does.
- Elements like navigation, footer widget, sidebars etc can all be removed via simple hooks.
- If a customer _really_ wants to create their own customized checkout (perhaps they don't like what's being offered), they can do by creating their own page template and including it within the child theme.

**Comment by sumobi** [comment]
I've considered a few different option names such as "enhanced checkout", "simple checkout" and "slim checkout" but "Distraction-free Checkout" seems to best describe what it does. It's also used frequently when discussing higher checkout conversions.

**Comment by sumobi** [comment]
Something like this, the option copy could use some tweaking. 

Not shown: The footer widgets removed and the copyright notice centered.
___
Default checkout page:

![screen shot 2017-05-25 at 5 26 36 pm](https://cloud.githubusercontent.com/assets/52581/26437144/688f49ac-416f-11e7-9290-9cc5eb88631a.png)

P.S if the customer wants to remove the sidebar at checkout (but leave everything else on), they can simply assign the no sidebar or slim page template to the checkout.

___
Distraction Free Checkout enabled:

![screen shot 2017-05-25 at 5 26 50 pm](https://cloud.githubusercontent.com/assets/52581/26437143/6886d876-416f-11e7-887a-a02f5f129f03.png)

**Comment by pippinsplugins** [comment]
Love it.
