### ISSUE TITLE
Make widget classes pluggable

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#110]
It would be useful to be able to override the parent theme widgets via a child theme, this could be achieved by wrapping them in an `if ! class_exists` function to make the widgets pluggable.

**Comment by amdrew** [comment]
What kinds of modifications do you see being needed that would require a copy of the entire widget class?

If it's adding new options to the widget, then hooks can be added to make that happen. Much easier to maintain. If the entire widget class is copied to the child theme, it won't miss out on bug fixes or new functionality.

If it's removing existing options, then it would be better to simply unhook the existing widget and register a new one from the child theme.

**Comment by davidsherlock** [comment]
@amdrew, it's additions such as adding new options and output on the sidebar. I'm good with hooks to achieve this!

Removing options isn't required.

**Comment by mindctrl** [comment]
There are some filters and actions in the main `WP_Widget` class that may allow you to do what you want without adding them to the theme.

**Comment by amdrew** [comment]
Thanks for the reminder @mindctrl 👍 

You'll be able to use the `in_widget_form` action hook and `widget_update_callback` filter hook to add a new field and save it.

**Comment by davidsherlock** [comment]
@amdrew, you couldn't by any chance post an example of how to achieve this (including saving and outputting) to the Themedd code snippets repo? Not much documentation online on how to properly achieve this.

Tried to get this working for about 2 hours and failed miserably...

**Comment by amdrew** [comment]
@davidsherlock Absolutely! I can put something together, though I can't tell you when at this point.

**Comment by amdrew** [comment]
@davidsherlock Show me what have so far and I'll see if I can spot where you went wrong!

**Comment by davidsherlock** [comment]
@amdrew, this actually broke the sidebars for some reason (haven't looked into it much...). But here is what I have so far:

```
/**
 * Place any custom functionality/code snippets below.
 */

 function themedd_download_details_add_options( $widget, $return, $instance ) {

     if ( 'themedd_download_details' == $widget->id_base ) {

       // Display the description option.
       $description = isset( $instance['downloads'] ) ? $instance['downloads'] : '';
       ?>
         <p>
     			<input type="checkbox" id="<?php echo esc_attr( $this->get_field_id( 'downloads' ) ); ?>" name="<?php echo esc_attr( $this->get_field_name( 'downloads' ) ); ?>" <?php checked( $instance['downloads'], true ); ?>/>
     			<label for="<?php echo esc_attr( $this->get_field_id( 'downloads' ) ); ?>"><?php _e( 'Show number of downloads', 'themedd' ); ?></label>
     		</p>
       <?php
     }
 }
 add_filter('in_widget_form', 'themedd_download_details_add_options', 10, 3 );


 function themedd_download_details_save_options( $instance, $new_instance ) {

     // Is the instance a nav menu and are descriptions enabled?
     if ( isset( $new_instance['themedd_download_details'] ) && !empty( $new_instance['downloads'] ) ) {
         $new_instance['downloads'] = 1;
     }

     return $new_instance;
 }
add_filter( 'widget_update_callback', 'themedd_download_details_save_options', 10, 2 );
```

Similarly, i have no clue how to output the new option onto the widget even if the above did work! :) Any guidance will be good...

**Comment by amdrew** [comment]
@davidsherlock 

Very close! `in_widget_form` is an action hook, so change it to `add_action`. That's the function that will output your new option into the widget.

**Comment by amdrew** [comment]
Oh and `$this` doesn't exist inside your `themedd_download_details_add_options()` function for setting the field ID. You'll need to construct the right `name` and `id` attribute by using some values available to use inside `$widget`. Hint, the id base and number.

**Comment by davidsherlock** [comment]
@amdrew, I changed it to this but on the widgets page the sidebars have all disappeared:

```
/**
 * Place any custom functionality/code snippets below.
 */

 function themedd_download_details_add_options( $widget, $return, $instance ) {

     if ( 'themedd_download_details' == $widget->id_base ) {

       // Display the description option.
       $description = isset( $instance['downloads'] ) ? $instance['downloads'] : '';
       ?>
         <p>
     			<input type="checkbox" id="<?php echo esc_attr( get_field_id( 'downloads' ) ); ?>" name="<?php echo esc_attr( get_field_name( 'downloads' ) ); ?>" <?php checked( $instance['downloads'], true ); ?>/>
     			<label for="<?php echo esc_attr( get_field_id( 'downloads' ) ); ?>"><?php _e( 'Show number of downloads', 'themedd' ); ?></label>
     		</p>
       <?php
     }
 }
add_action('in_widget_form', 'themedd_download_details_add_options', 10, 3 );


 function themedd_download_details_save_options( $instance, $new_instance ) {

     // Is the instance a nav menu and are descriptions enabled?
     if ( isset( $new_instance['themedd_download_details'] ) && !empty( $new_instance['downloads'] ) ) {
         $new_instance['downloads'] = 1;
     }

     return $new_instance;
 }
add_filter( 'widget_update_callback', 'themedd_download_details_save_options', 10, 2 );
```

**Comment by davidsherlock** [comment]
Could you post a really quick code example of how to achieve this? Will buy you a beer sometime if you can!

I'm still somewhat of a hacky coder who' learns as he goes, hence the above mess :) ha!

**Comment by spencerfinnell** [comment]
```php
function themedd_download_details_add_options( $widget, $return, $instance ) {
	if ( 'themedd_download_details' !== $widget->id_base ) {
		return;
	}

	$downloads = isset( $instance['downloads'] );
?>

<p>
	<input type="checkbox" id="<?php echo esc_attr( $widget->get_field_id( 'downloads' ) ); ?>" name="<?php echo esc_attr( $widget->get_field_name( 'downloads' ) ); ?>" <?php checked( $downloads, true ); ?>/>
	<label for="<?php echo esc_attr( $widget->get_field_id( 'downloads' ) ); ?>"><?php _e( 'Show number of downloads', 'themedd' ); ?></label>
</p>

<?php
}
add_action('in_widget_form', 'themedd_download_details_add_options', 10, 3 );

function themedd_download_details_save_options( $instance, $new_instance ) {
	// Is the instance a nav menu and are descriptions enabled?
	if ( isset( $new_instance['themedd_download_details'] ) && !empty( $new_instance['downloads'] ) ) {
		$new_instance['downloads'] = 1;
	}

	return $new_instance;
}
add_filter( 'widget_update_callback', 'themedd_download_details_save_options', 10, 2 );
```

**Comment by davidsherlock** [comment]
@spencerfinnell, what a legend! Thanks man :) 

One quick question, how do I output (append) to the on the frontend via the public function widget( $args, $instance )? For example, adding this:

```
$categories = themedd_edd_download_categories( $post->ID );

if ( $categories ) : ?>
	<li class="downloadDetails-categories">
	<span class="downloadDetails-name"><?php _e( 'Categories:', 'themedd' ); ?></span>
	<span class="downloadDetails-value"><?php echo $categories; ?></span>
	</li>
<?php endif; ?>

**Comment by davidsherlock** [comment]
@spencerfinnell, a strange issue is happening...

When you select the option it disables all the other checkboxes! Any ideas?

![screenshot 2017-08-30 23 42 52](https://user-images.githubusercontent.com/22668877/29898318-05f8a4b8-8ddd-11e7-834e-160eb4e72653.png)

**Comment by spencerfinnell** [comment]
Check your update logic against https://github.com/easydigitaldownloads/themedd/blob/master/includes/compatibility/edd/class-widget-download-details.php#L248-L261

Look at which old/new is being compared.

Hooks will need to be added on the frontend to output any of the information in a reasonable way.
