### ISSUE TITLE
Add ability to set favicon

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#112]
As per the title, it would be useful within the customizer to be able to set the favicon.

**Comment by amdrew** [comment]
You can do this already from the "site identity" section. Is it not showing for you @davidsherlock?

<img width="369" alt="screenshot 2017-08-27 11 23 40" src="https://user-images.githubusercontent.com/52581/29745850-3f8105a6-8b1a-11e7-9847-8d913351be5b.png">

**Comment by davidsherlock** [comment]
Sorry @amdrew, I'll blame that on having a drink tonight...
