### ISSUE TITLE
Restore basket link layout issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#113]
The following shows on the empty cart screen:

![screenshot 2017-08-30 01 32 30](https://user-images.githubusercontent.com/22668877/29850121-2a9f6654-8d23-11e7-8318-b6ee1931b044.png)

Feel the overall look and layout could be improved of the link itself.

**Comment by amdrew** [comment]
👍 Thanks, will check it out

**Comment by amdrew** [comment]
Moved it onto the same line at the empty cart message.

<img width="552" alt="screenshot 2017-09-05 00 41 54" src="https://user-images.githubusercontent.com/52581/30026942-0cf427ac-91d3-11e7-83f0-a323c674f55f.png">

Also introduced a `edd-empty-cart` body class when the cart is empty, and renamed the opposite body class from `items-in-cart` to `edd-items-in-cart` for consistency.
