### ISSUE TITLE
edd template file hook request

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#114]
@amdrew, I suggested this on the EDD core repo, but it's not something they are going to action anytime soon and wanted to think on it more.

Long story short, I am developing an EDD audio player plugin that integrates seamlessly with Themedd and is ultra lightweight (using mediaelement.js and no dependencies - just some clever javascript and backend PHP). Hoping to sell this plugin when it's finished in a week or two as well (maybe even on the EDD store if they accept it!). 

Would you be able to add a custom EDD template file into Themedd with the following action hook in `shortcode-content-image.php`:

```
<?php if ( function_exists( 'has_post_thumbnail' ) && has_post_thumbnail( get_the_ID() ) ) : ?>
	<div class="edd_download_image">
		<a href="<?php the_permalink(); ?>">
			<?php echo get_the_post_thumbnail( get_the_ID(), 'thumbnail' ); ?>
		</a>
		<?php do_action( 'edd_download_image_overlay' ); ?>
	</div>
<?php endif; ?>
```

This allows me to do this (just a placeholder for reference):

![screenshot 2017-08-30 01 40 21](https://user-images.githubusercontent.com/22668877/29850328-abeee1de-8d24-11e7-9ac6-065ef6262da5.png)

**Comment by davidsherlock** [comment]
You can obviously decide what to call it yourself if you decide to include it! Would just be useful to have so i can have overlay icons/buttons on the images when needed by my plugin.

**Comment by amdrew** [comment]
Sounds like a nice plugin! Is it going to work with all EDD themes, or just Themedd (and your fork)?

If all EDD themes, then the obvious problem is that even if the action hook is added to Themedd, the plugin won't work for anyone else using a different theme.

I can see how the hook would be useful but I'm a little hesitant at this point to create yet another template file inside Themedd for just the 1 use-case. If Themedd needed the hook itself then it would be a different story. Themedd is geared more at being a "starting point" - I'm actually working on removing a couple more template files inside Themedd since they shouldn't really be there.

Can I ask what will replace the grey square? Something like a play button or such? If it's related to a media player which requires `mediaelement.js` then it would be much better to inject the div with JS since JS is already a dependency for playing the music. That way, it will work across all EDD themes :)

Let me know!

**Comment by davidsherlock** [comment]
@amdrew, I want it to work with all themes but it will be designed to work best (in terms of styling) with Themedd. I am going to have a backup place for the play button for people not using Themedd though. It's not locked in anyway to my theme, hence why I wanted to make it a plugin instead of a theme to keep the data modular and allow customers to use any theme they wish with the plugin.

There isn't actually any JS being loaded (or injected into divs) other than 2 files loaded conditionally if audio is assigned to the download - mediaelement.js and a custom js playlist file that sends events to the player at the bottom. It's all done via this approach on a per download basis:

```
<ul class="tracks" style="display: none;">
        <li class="collection-track playing" data-link="http://themeddplus.dev/wp-content/uploads/edd/2017/08/PLUCKS-LEADS-DEMO.mp3">
        <span class="number">1</span>
        <span class="track-name">PLUCKS - LEADS DEMO</span>
        <span class="duration"></span>
        </li>
        <li class="collection-track" data-link="http://themeddplus.dev/wp-content/uploads/edd/2017/08/Take_Off_and_Shoot_a_Zero.mp3">
        <span class="number"></span>
        <span class="track-name">Take Off and Shoot a Zero</span>
        <span class="duration"></span>
        </li></ul>
```
I built a back end metabox so customers can assign audio files to their downloads and then it renders them on the frontend. Here is how a product page audio playlist looks for example:

<img width="921" alt="screenshot 2017-08-30 05 32 34" src="https://user-images.githubusercontent.com/22668877/29855570-b4d9d608-8d44-11e7-814f-26a0d29774a3.png">

**Comment by davidsherlock** [comment]
@amdrew, is there anyway for the plugin itself to override (and use) my custom template as per above? I can't think of any other solution to get the buttons over the image.

**Comment by amdrew** [comment]
Ahh excellent, I like the idea on the backup position!

Let me ponder on that for a bit.

**Comment by amdrew** [comment]
@davidsherlock I can't think of a way to do that

**Comment by davidsherlock** [comment]
I hope this gets added to core, as it's pretty common to have overlays on the download images for a variety of reasons.

In the meantime I will use a work around, putting the button before (or after) the title and include some documentation with my plugin on how to add a new template file for the purpose of the improved UX.

Thanks anyway @amdrew!

**Comment by amdrew** [comment]
👍
