### ISSUE TITLE
Fix author info boxes with short bios

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#115]
When an author has a short bio, it looks like the following:

<img width="855" alt="screenshot 2017-08-30 14 51 10" src="https://user-images.githubusercontent.com/52581/29853330-6e9ebca4-8d93-11e7-8b67-86f5fbea1d98.png">

PR has been submitted here: https://github.com/easydigitaldownloads/themedd/pull/111

**Comment by amdrew** [comment]
@galengidman Appreciate the PR! I think it's best however if we remove the floats altogether and use flexbox for a much cleaner solution. Would you like to submit a new PR using flexbox?

**Comment by amdrew** [comment]
This should be as simple as adding `display: flex` on `.author-info` at the `@screen-sm-min` breakpoint. Will also need a right margin on the avatar.

**Comment by galengidman** [comment]
If you run `npm ls` what do you get for versions on the Grunt Autoprefixer tree? I get this:

```├─┬ grunt-autoprefixer@3.0.4
│ ├─┬ autoprefixer-core@5.2.1
│ │ ├── browserslist@0.4.0
│ │ ├── caniuse-db@1.0.30000718
│ │ └── num2fraction@1.2.2
│ ├─┬ chalk@1.0.0
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@1.0.3
│ │ │ └── ansi-regex@1.1.1
│ │ ├── strip-ansi@2.0.1
│ │ └── supports-color@1.3.1
│ ├── diff@1.3.2
│ └─┬ postcss@4.1.16
│   ├── es6-promise@2.3.0
│   ├── js-base64@2.1.9
│   └─┬ source-map@0.4.4
│     └── amdefine@1.0.1```

**Comment by amdrew** [comment]
```
─┬ grunt-autoprefixer@3.0.4
│ ├─┬ autoprefixer-core@5.2.0
│ │ ├─┬ browserslist@0.4.0
│ │ │ └── caniuse-db@1.0.30000203 deduped
│ │ ├── caniuse-db@1.0.30000203
│ │ ├── num2fraction@1.1.0
│ │ └─┬ postcss@4.1.11
│ │   ├── es6-promise@2.1.1
│ │   ├── js-base64@2.1.8
│ │   └─┬ source-map@0.4.2
│ │     └── amdefine@0.1.0
```

**Comment by galengidman** [comment]
@amdrew - I can't get this frickin' Autoprefixer stuff figured out. Since it's a small fix, hopefully you can get it handled? Sorry about that. :(

**Comment by davidsherlock** [comment]
@galengidman, not an ideal setup but I prefer using CodeKit for handling autoprefixer and LESS compilation. Might be worth checking out if you use a mac. 

You can change the version string in the settings. You need to go 5 versions behind to the get the correct prefixes.

**Comment by amdrew** [comment]
@galengidman No problem at all! Hopefully it's not something in the theme's config file.

**Comment by amdrew** [comment]
The above commit should do the trick:

<img width="317" alt="screenshot 2017-09-05 11 53 25" src="https://user-images.githubusercontent.com/52581/30040263-172c5ad8-9231-11e7-81d1-9d78e54f3c38.png">

<img width="843" alt="screenshot 2017-09-05 11 53 37" src="https://user-images.githubusercontent.com/52581/30040262-16fd166a-9231-11e7-95a8-99e5b4c29515.png">

<img width="822" alt="screenshot 2017-09-05 11 56 19" src="https://user-images.githubusercontent.com/52581/30040280-402ebb2e-9231-11e7-878f-3ab7f5d2c13e.png">

**Comment by galengidman** [comment]
Thanks Andrew. Sorry I wasn't able to be more help here.
