### ISSUE TITLE
Theme Check Warnings

### ISSUE THREAD

**Issue by philiparthurmoore** [easydigitaldownloads/themedd#117]
<img width="1476" alt="2017-08-31_15-40-36" src="https://user-images.githubusercontent.com/28684/29914521-0bfb2d3c-8e63-11e7-9f34-347eea70da50.png">

**Comment by amdrew** [comment]
Thanks @philiparthurmoore!

I've run it through theme check myself, have plans to fix up those required CSS classes (https://github.com/easydigitaldownloads/themedd/issues/12) and warnings so it can be prepped for wordpress.org.

**Comment by philiparthurmoore** [comment]
Awesome. Thanks, Andrew. Lovely work.

**Comment by amdrew** [comment]
Thanks @philiparthurmoore
