### ISSUE TITLE
Customizer: Button text color overwritten by link color

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/themedd#118]
Inside the customizer, the button color seems to be overwritten by the link color entered before. On the frontend it works fine.

<img width="1416" alt="bildschirmfoto 2017-09-01 um 10 55 34" src="https://user-images.githubusercontent.com/2278756/29962636-239b70ea-8f04-11e7-8e1c-235c094e00a0.png">

**Comment by amdrew** [comment]
Thanks @flowdee, will check it out

**Comment by amdrew** [comment]
@flowdee Give that latest commit a go, the link color should not affect any buttons.

**Comment by flowdee** [comment]
Yep, it's gone. Thanks Andrew!  👍
