### ISSUE TITLE
Extend the themedd_edd_download_categories and themedd_edd_download_tag functions to accept parameters

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#120]
I extended the `themedd_edd_download_categories` and `themedd_edd_download_tags` functions to allow the `before`, `separator` and `after` parameters, allowing for more control over the output (for example - removing the comma delimitation to use `divs` instead for the tags on other parts of the theme).

Particular example would be something like this: https://creativemarket.com/quilltypeco/1754201-Cache-Vintage-Font-Family

I submitted a PR (#119) with the additions.

**Comment by amdrew** [comment]
Not sure what I'm looking at with the font you linked to but will check out the PR, thanks!

**Comment by amdrew** [comment]
Merged 👍
