### ISSUE TITLE
Add hooks and filters to public function widget

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#121]
To allow the Themedd widgets to be properly extended, the `themedd_edd_download_details_options` array needs a filter to allow proper extension. Same goes for the author widget.

I would also like two actions within the `<ul>` at the top and bottom to allow adding additional output to the widget display. Optionally two more hooks could be added outside of the widget `<ul>` above and below the widget to allow more flexible placement.

Off-topic, here is the code to add options to the `Themedd: Download Details` widget (I will update this to be a more complete example once the hooks and filters are added and post it to the Themedd code library for others):

```
 /**
  * Add new "Downloads" checkbox option to to Themedd Download Details widget
  */
 function themedd_child_download_details_add_download_option( $widget, $return, $instance ) {

   // Verify widget instance
 	if ( 'themedd_download_details' !== $widget->id_base ) {
 		return;
 	}

 	$downloads = isset( $instance['downloads'] );
 ?>

 <p>
 	<input type="checkbox" id="<?php echo esc_attr( $widget->get_field_id( 'downloads' ) ); ?>" name="<?php echo esc_attr( $widget->get_field_name( 'downloads' ) ); ?>" <?php checked( $downloads, true ); ?>/>
 	<label for="<?php echo esc_attr( $widget->get_field_id( 'downloads' ) ); ?>"><?php _e( 'Show number of downloads', 'themedd-child' ); ?></label>
 </p>

 <?php
 }
 add_action('in_widget_form', 'themedd_child_download_details_add_download_option', 10, 3 );

 /**
  * Save new "Downloads" option and maintain original options
  */
 function themedd_child_download_details_save_download_option( $instance, $new_instance ) {
  $new_instance['title']      = ( ! empty( $instance['title'] ) )  ? strip_tags( $instance['title'] ) : '';
  $new_instance['published']  = ! empty( $instance['published'] )  ? true : false;
  $new_instance['sales']      = ! empty( $instance['sales'] )      ? true : false;
  $new_instance['categories'] = ! empty( $instance['categories'] ) ? true : false;
  $new_instance['tags']       = ! empty( $instance['tags'] )       ? true : false;

  if ( themedd_is_edd_sl_active() ) {
    $new_instance['version'] = ! empty( $instance['version'] ) ? true : false;
  }
   // Is the instance a nav menu and are descriptions enabled?
  if ( isset( $new_instance['themedd_download_details'] ) && !empty( $new_instance['downloads'] ) ) {
  $new_instance['downloads'] = 1;
  }

  return $new_instance;
 }
add_filter( 'widget_update_callback', 'themedd_child_download_details_save_download_option', 10, 2 );

```

**Comment by amdrew** [comment]
@davidsherlock Added hooks in #109 which will help: https://github.com/easydigitaldownloads/themedd/issues/109#issuecomment-327985296

> To allow the Themedd widgets to be properly extended, the themedd_edd_download_details_options array needs a filter to allow proper extension. Same goes for the author widget.

The array inside the `themedd_edd_download_details_options()` function does have a filter (as does the author equivalent): https://github.com/easydigitaldownloads/themedd/blob/master/includes/compatibility/edd/functions-download-details.php#L38

Are you perhaps referring to this array that is being passed to the above function? https://github.com/easydigitaldownloads/themedd/blob/master/includes/compatibility/edd/class-widget-download-details.php#L76-L83

**Comment by amdrew** [comment]
I've added some new filters and hooks in the widget classes. Going to close this in favor of #109.
