### ISSUE TITLE
Author archive page should use slim page template when no sidebar active

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#125]
By default the blog archive page uses the slim page template, along with the single posts when no sidebar is active.

However the author archive page uses the full-width template, which breaks uniformity (specifically if you have a thumbnails smaller than the recommended featured image width). 

I recommend we adopt the same width/layout for the author page.

**Comment by amdrew** [comment]
👍

**Comment by amdrew** [comment]
@davidsherlock That should do it ^
