### ISSUE TITLE
Post-Navigation CSS a:hover color not being applied correctly

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/themedd#128]
Custom link color is not being applied correctly when the post-navigation link.

<img width="963" alt="bildschirmfoto 2017-09-06 um 10 59 28" src="https://user-images.githubusercontent.com/2278756/30103329-9b0a5c6c-92f2-11e7-9e0e-2ea93491f5f7.png">

All other content links work fine for me.

**Comment by davidsherlock** [comment]
On a similar topic, I walked into an issue where I wanted to add a customizer control for a pseudo element (:before), but since this isn't' part of the DOM, I had to use this workaround:

```
	// Typography subtitle accent color.
	wp.customize( 'colors[typography_subtitle_accent_color]', function( value ) {
		value.bind( function( to ) {

				var style, el;

				// Build the style element
				style = '<style class="subtitle-accent">.subtitle:before { background: ' + to + '; }</style>';

				// Look for a matching style element that might already exist
				el =  $( '.subtitle-accent' );

				// Add the style element into the DOM or replace the matching style element that already exists
				if ( el.length ) {
						el.replaceWith( style ); // Style element already exists, so replace it
				} else {
						$( 'head' ).append( style ); // Style element doesn't exist so add it
				}
		} );
	} );
```

A similar approach may be required for the hover elements.

**Comment by amdrew** [comment]
@flowdee Got it, thanks. Looks like it's not working in customizer or front-end.

**Comment by flowdee** [comment]
For me I experienced it on the frontend

**Comment by amdrew** [comment]
That should fix it
