### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#13]
@easydigitaldownloads/core-devs 

Theme is more or less ready for some testing. Import the theme test data (https://codex.wordpress.org/Theme_Unit_Test) and go to town. Please open a new issue for anything you spot.

Particularly looking for:

1. Plugin compatibility issues, see https://github.com/easydigitaldownloads/themedd/issues/4. Probably missed a whole bunch of stuff for FES
2. General styling issues and consistency

Sorry, no documentation just yet.

**Comment by SDavisMedia** [comment]
I'll give it a spin this weekend.
