### ISSUE TITLE
.edd_download_inner tweak suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#131]
The padding of 1.5rem is a bit generous in my opinion; I feel the following looks better and focuses more on the content (showcasing the featured product images):

```
.edd_download_inner {
    padding: 1rem;
}
```

**Comment by SDavisMedia** [comment]
This adjustment is not as simple as it seems. When designing a site, things are (or at least should be) lined up horizontally and vertically across multiple elements on the entire page, not just the elements that are close to each other.

In this case, reducing (adjusting in general) the padding of `.edd_download_inner` throws it out of line with other site elements, like elements in the header (see the ruler lines):

<img width="1342" alt="screenshot 2017-09-07 08 46 10" src="https://user-images.githubusercontent.com/2359131/30172228-0b193e18-93a9-11e7-85c6-289a93db784a.png">

Adjusting that padding means either introducing an inconsistency, _or_ adjusting the width of all site elements... which then affects things like the general width of the site content, CPL for typography, and just the overall vibe and feel of the design. I'm willing to bet @amdrew decided on the overall design vibe itself first, and then made the content follow suit, resulting in the chosen padding for those elements.

**Comment by davidsherlock** [comment]
Definitely not disputing that @SDavisMedia, and I'm aware of what you are saying for sure.

If @amdrew doesn't agree, then I will just include it my child theme - no big issue really. Personal preference in a lot of ways anyway when it comes to design and alike.

**Comment by amdrew** [comment]
@davidsherlock Child theme please 👍

**Comment by davidsherlock** [comment]
On it boss! haha
