### ISSUE TITLE
Checkout cart is showed on mobiles

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/themedd#133]
I have disabled checkout icon and link from customizer and it completely disappear from the secondary menu (as expected) but it still appearing at the mobile menu

**Comment by amdrew** [comment]
@rubengc Thanks for spotting that. I don't see anything in the mobile menu, but I do see an empty list item for the cart that shouldn't be there. I'll fix and we'll see if that then fixes it for you too:

<img width="523" alt="screenshot 2017-09-08 13 02 12" src="https://user-images.githubusercontent.com/52581/30191619-1125720c-9496-11e7-92a7-0bd0eae895c4.png">

**Comment by amdrew** [comment]
@rubengc ^ See if that fixes it for you

**Comment by rubengc** [comment]
Thanks @amdrew for your fast reply

I will test It on come back to home

Just a question, which version is targeted the theme updater?

**Comment by amdrew** [comment]
@rubengc Sorry, I don't quite understand your question. When v1.0.1 is released you'll be able to update from 1.0 to 1.0.1, is that your question?

**Comment by rubengc** [comment]
My bad, I see a lot of commits and bugfixes and I think that updates are not configure yet

**Comment by amdrew** [comment]
No problem at all. GitHub is for development purposes so there will be lots of activity.

**Comment by rubengc** [comment]
Tested on latest version and I can confirm this issue was fixed

Thanks @amdrew 

Note: On themedd child repo, parent theme on wp_enqueue_style should be `themedd-style` instead of `themedd`

**Comment by amdrew** [comment]
@rubengc Great to hear!

> Note: On themedd child repo, parent theme on wp_enqueue_style should be themedd-style instead of themedd

I'd be interested to hear your reasoning. `themedd` is the parent theme's ID as per:

`wp_enqueue_style( 'themedd', get_theme_file_uri( 'style' . $suffix . '.css' ), array(), THEMEDD_VERSION );`

Changing `themedd` to `themedd-style` in the child style would also still work, but the ID loaded in the HTML would then be `themedd-style-css` instead of `themedd-css`. Personally I'd like to keep it consistent with the parent theme. I can't see a reason why changing it to `themedd-style` would be better?

Let me know!

**Comment by rubengc** [comment]
Ah yes, I remember why

`get_theme_file_uri` returns the style.css located at child theme (it also happens with the minified version, if you have one)

Check:
```
wp_enqueue_style( 'themedd', get_theme_file_uri( 'style' . $suffix . '.css' ), array(), THEMEDD_VERSION );

function get_theme_file_uri( $file = '' ) {
	$file = ltrim( $file, '/' );

	if ( empty( $file ) ) {
		$url = get_stylesheet_directory_uri();
	} elseif ( file_exists( get_stylesheet_directory() . '/' . $file ) ) { // themedd-child/style.css exists? of course...
		$url = get_stylesheet_directory_uri() . '/' . $file;
	} else {
		$url = get_template_directory_uri() . '/' . $file;
	}

	/**
	 * Filters the URL to a file in the theme.
	 *
	 * @since 4.7.0
	 *
	 * @param string $url  The file URL.
	 * @param string $file The requested file to search for.
	 */
	return apply_filters( 'theme_file_uri', $url, $file );
}
```

For this reason I have it enqueued as themedd-style

Anyway, you should register themedd css using `get_template_directory_uri` to avoid this error (keep in mind themedd functions.php is loaded, so you asset enqueue is the first one to happen)

**Comment by rubengc** [comment]
Ah, You will notice this error if you have SCRIPT_DEBUG enabled or if you setup your child theme with a style.min.css

Hope it helps

**Comment by amdrew** [comment]
I'm not 100% following, what error are you seeing? Does using the child theme (without any modifications) not work for you in terms of loading the CSS? 

If you can share your code I might get a better understanding of the issue you are seeing.

**Comment by rubengc** [comment]
I will try to explain It better (I know my english is terrible)

`get_theme_file_uri` tries to return the uri of a desired file prioritizing existent files from the child theme

If you setup a WordPress install with Themedd and themedd-child repos (without defining SCRIPT_DEBUG as true) child theme will load themedd style.min.css and Themedd child style.css as expected

But there is two ways to provoque a duplicated Themedd child style enqueue:
1 - If you setup SCRIPT_DEBUG as true, then themedd child style.css will be enqueued two times, because `get_theme_file_uri` will receive 'style.css' as parameter and It will return the uri from the child theme
2 - If you create a minified version of your theme named 'style.min.css' then will happen the same described before, `get_theme_file_uri` will return the uri from the child theme instead of the style located at parent theme

For this, you need to update your enqueue functions with `get_template_directory_uri` to be sure that themedd assets will be enqueued succesfully from themedd
