### ISSUE TITLE
Fatal error: Can't use function return value in write context

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/themedd#137]
A user reported this fatal:

Fatal error: Can't use function return value in write context in /home1/ionblue/public_html/pulpfictionbook.store/wp-content/themes/themedd/includes/compatibility/edd/actions.php on line 90

**Comment by amdrew** [comment]
Ticket:
https://secure.helpscout.net/conversation/428988544/66433/?folderId=180502

**Comment by amdrew** [comment]
@pippinsplugins Thanks for the PR! There's another 2 instances where it could produce the same fatal error, will get those sorted also.
