### ISSUE TITLE
"Only for use in Download Sidebar" alert showing inside customizer

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#140]
The `Only for use in Download Sidebar` alerts are showing for both widgets while inside the customizer and on the download sidebar. This is most likely due to the CSS class which is probably different when on the default widgets page vs being inside the customizer.

<img width="329" alt="screenshot 2017-09-12 13 27 41" src="https://user-images.githubusercontent.com/52581/30303769-2ad574ec-97be-11e7-9bdb-1a81dd8a1854.png">

**Comment by amdrew** [comment]
The CSS rule that hides the message on the widgets page targets a div with an ID of `sidebar-download`. This div doesn't exist inside the customizer section (the admin.css is still correctly loaded however). We'll just need to use an extra selector to make sure it's hidden within the customizer while on the `Download Sidebar`.

**Comment by amdrew** [comment]
Added a new `#sub-accordion-section-sidebar-widgets-sidebar-download .themedd-widget-usage` selector.

**Comment by SDavisMedia** [comment]
I should probably do the same thing, huh...

**Comment by amdrew** [comment]
💯
