### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#144]
Themedd needs a simple solution for searching, before https://github.com/easydigitaldownloads/themedd/issues/43 or https://github.com/easydigitaldownloads/themedd/issues/30 can be possible. 

Want to keep it as simple as possible. No flashy effects, just a simple input field and search button in the header (maybe an icon). It will also be easy to customize if the child theme needs to open it up in a modal window, slide it out etc.

It will be turned off by default, with a customizer option to turn it off.

**Comment by davidsherlock** [comment]
Was going to suggest exactly this! Something very simple and clean. Ideally also with an advanced search results option to maintain the grid layout for the downloads, with the posts/pages at the bottom. Since most people will be using Themedd for ecommerce purposes

**Comment by amdrew** [comment]
👍 Any advanced search result functionality will come later in the linked issues above. This is only for a simple search option.

**Comment by amdrew** [comment]
Quick update. By default it will show next to the secondary menu. Will most likely place a search icon inside the search box on the right side, so a user knows to click something. 

At the moment it says "Search products..." and will only search downloads, however it will likely search everything by default and perhaps it's an option to only search products. 

This will tie in somehow with the advanced search functionality. Might also make the search field a tad shorter in height.

<img width="1340" alt="screenshot 2017-09-20 16 21 08" src="https://user-images.githubusercontent.com/52581/30626735-dbc94212-9e1f-11e7-97c6-4bea686cdbe1.png">

___

And on mobile it would be added to the top of the menu, and be 100% wide:

<img width="324" alt="screenshot 2017-09-20 16 21 35" src="https://user-images.githubusercontent.com/52581/30626734-dba040ce-9e1f-11e7-9d1c-360b6c7f81f3.png">

**Comment by rubengc** [comment]
This can be done with a free plugin, and results will be loaded using ajax:
https://wordpress.org/plugins/edd-ajax-search/

**Comment by davidsherlock** [comment]
@amdrew, I agree with having the search in the menu(s) as an option, but ultimately felt a search field (ideally with categories below like EDD site) above the download lists and on the taxonomy pages would be more useful for e-commerce stores, since the majority of people are going to be buying products:

![screenshot 2017-09-20 14 03 03](https://user-images.githubusercontent.com/22668877/30645171-c3c597d2-9e0c-11e7-81a4-0fe21f7249db.png)

This would hook in above the download lists and could be enabled optionally from the customizer or filtered for specific pages via a filter.

**Comment by amdrew** [comment]
@rubengc The end-user shouldn't need to install a plugin to show a simple search form on their site. WordPress provides search functionality out of the box (with a shortcode/function etc). This issue is merely exposing that search form in a nice way which is very common to eCommerce websites. That said, your plugin looks nice and would be well-suited for those looking for an ajax search.

**Comment by amdrew** [comment]
@davidsherlock As per https://github.com/easydigitaldownloads/themedd/issues/144#issuecomment-330489900 what you've suggested seems like it should be posted on https://github.com/easydigitaldownloads/themedd/issues/43.

**Comment by amdrew** [comment]
Added a small SVG icon on the right of the input field which will submit the search form. Overall, the input field is shorter in height. For mobile, the font-size has been increased to 16px to prevent iOS zooming in by default.

___

Desktop:

<img width="603" alt="screenshot 2017-09-29 13 56 00" src="https://user-images.githubusercontent.com/52581/30996540-19969bee-a51e-11e7-9180-37162d888c3a.png">

___

And mobile:

<img width="327" alt="screenshot 2017-09-29 13 56 16" src="https://user-images.githubusercontent.com/52581/30996539-197cc48a-a51e-11e7-8bf4-f1b2fa1824eb.png">

___

**Comment by amdrew** [comment]
Since the header background color can be changed via the theme customizer I've decided to remove the borders from the search field and make the input field a light grey by default. This provides greater flexibility with custom colors and makes the form easier to see. For example, we now don't need to create a color control for the border color. That said, we'll need some new color controls for:

1. The search field background color
2. The search field text color
3. The search field icon color

Here's the updated search field:

<img width="265" alt="screenshot 2017-09-29 18 56 15" src="https://user-images.githubusercontent.com/52581/31003974-dd0a0310-a54e-11e7-91c1-70a8c29f53a3.png">

The work done in this issue will also standardize the look of all search forms across the theme.

Things left to do on this:

- [ ] Add customizer option under "Theme Options" to turn on the search field in the header
- [ ] Set up selective refresh for the new customizer option
- [ ] Add required customizer color controls
- [ ] Add new searchform.php file
- [ ] Additional testing

**Comment by amdrew** [comment]
Quick and dirty example of the new color options for the header search box:

<img width="322" alt="screenshot 2017-09-30 15 16 18" src="https://user-images.githubusercontent.com/52581/31041459-558c4d68-a5f2-11e7-9456-da63106a0344.png">

<img width="425" alt="screenshot 2017-09-30 15 15 48" src="https://user-images.githubusercontent.com/52581/31041464-6803d344-a5f2-11e7-9c19-2b7ec9a3156f.png">

The mobile devices menu has its own set of color options for the search since the background color behind the search field could be different.

**Comment by amdrew** [comment]
Merging into master for some more testing
