### ISSUE TITLE
Pagination not working with custom EDD_SLUG

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/themedd#145]
Pagination on [downloads] shortcode is not working with a custom EDD_SLUG

Tested with a wordpress default theme and it works perfectly, just fails wihen themedd is enabled

Custom slug: 'add-ons'

**Comment by amdrew** [comment]
@rubengc Weird, should work fine. Will check it out. Did you flush your permalinks after changing the slug?

**Comment by amdrew** [comment]
Works fine for me so far with a custom slug of `add-ons`. Can you show me how it fails? Screenshots of your setup if you can.

**Comment by rubengc** [comment]
I will try to explain everything

I have the EDD_SLUG 'add-ons' but I want a cool archive page adding some shortcodes and more info so I create a page with the post_name 'add-ons' to override themedd's archives page

Bit it does not works, so I disable the downloads archive (EDD_DISABLE_ARCHIVE to true) and yes, issue happens here, the [downloads] shortcode can not paginate

to let you check it there is the full config:
* Create a page with the  post_name 'add-ons' with the [downloads] shortcode as content
* define( 'EDD_SLUG', 'add-ons' );
* define( 'EDD_DISABLE_ARCHIVE', true );

Probably the issue comes from EDD instead from themedd

**Comment by amdrew** [comment]
Yep, not an issue with Themedd. If you switch to another theme you'll see it also doesn't work.
