### ISSUE TITLE
Themedd Demo Content

### ISSUE THREAD

**Issue by surjithctly** [easydigitaldownloads/themedd#148]
Is there a demo content available for Themedd? So it look like the screenshots. Because currently its blank when I did a fresh install.

**Currently on a fresh install**: [wp_fresh_install.jpg](https://user-images.githubusercontent.com/1884712/30870272-1956d42e-a301-11e7-9800-b65658bfaeab.png)

**What I need that to look like**: [themedd_demo.jpg](https://user-images.githubusercontent.com/1884712/30870270-14c7ee52-a301-11e7-9bb9-4498a38f4d74.png)

Thank you so much!

**Comment by davidsherlock** [comment]
@surjithctly, I actually released some sample data for Themedd today (since I develop WordPress themes and plugins). 

You can download it here if you are interested: https://github.com/davidsherlock/themedd-sample-data

The sample data includes over 30 different download products, pages, posts, etc.

**Comment by amdrew** [comment]
@surjithctly Sadly there isn't at this point (hoping to provide some in the near future). @davidsherlock Thanks for posting that!

**Comment by surjithctly** [comment]
@davidsherlock Thank you. Much better now. However, images were not downloaded because of your .dev URL.

**Comment by surjithctly** [comment]
@amdrew Any idea why the Purchase button not showing on the detail page? https://prnt.sc/gqa7tf

**Comment by amdrew** [comment]
@surjithctly I can't seem to replicate that issue, the purchase button shows fine. Correct, it should show when there are no widgets, can you double-check to see if there are any widgets in the download sidebar? 

If you're still having issues please open ticket and we'll track down why it's not showing for you: https://easydigitaldownloads.com/support/

**Comment by surjithctly** [comment]
@amdrew I have the Author Details and Download Info widget, However, when I removed both, it's showing the button. 

But my question is, How do I then add the Author Details and Download Info widget? I can see both 3 widgets working on your [screenshot](https://themedd.com/wp-content/themes/themedd-site/assets/images/home-screenshot-2.png): 

I've submitted the ticket also #67503.

**Comment by amdrew** [comment]
@surjithctly Thanks, replied with the solution (to add the EDD Download Details widget) :)
