### ISSUE TITLE
Account page

### ISSUE THREAD

**Issue by flowdee** [easydigitaldownloads/themedd#149]
Are you planning to add layout/styles for a proper account page layout - similar to affwp - too?

**Comment by davidsherlock** [comment]
I believe I can answer this (since I asked it previously) - basically, they plan to have a better account page functionality in EDD core rather than the theme.

**Comment by flowdee** [comment]
Thanks for the tip David.

**Comment by amdrew** [comment]
That's correct, here's the EDD issue: https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5398
