### ISSUE TITLE
Style Stripe gateway extension

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#15]
The latest release of the Stripe gateway has some elements that need CSS styling, namely at checkout and on the `[edd_profile_editor]` shortcode. Since Themedd removes EDD's styling, the Stripe CSS file does not load. 

It's been added manually but it would be nice to get some custom styling so everything looks consistent.

**Comment by sumobi** [comment]
Progress so far. 

@pippinsplugins @cklosowski Is there anywhere else the plugin adds styling that I may have missed?

## [edd_profile_editor] shortcode

### Manage Payment methods
![screen shot 2017-06-09 at 6 53 45 pm](https://user-images.githubusercontent.com/52581/26964373-3dfc31c8-4d45-11e7-9765-cc164731d878.png)

### Clicking to update an existing card:

![screen shot 2017-06-09 at 6 53 58 pm](https://user-images.githubusercontent.com/52581/26964426-811f8054-4d45-11e7-8fb4-181391d5f65a.png)

### Adding a new card:

![screen shot 2017-06-09 at 6 54 19 pm](https://user-images.githubusercontent.com/52581/26964425-8115cf78-4d45-11e7-999b-604f2f5bd0a4.png)

![screen shot 2017-06-09 at 6 54 32 pm](https://user-images.githubusercontent.com/52581/26964427-812b7a44-4d45-11e7-808f-9b0974697fd9.png)

## Checkout

![screen shot 2017-06-09 at 6 54 54 pm](https://user-images.githubusercontent.com/52581/26964480-c081c702-4d45-11e7-832a-76d23b57c263.png)

![screen shot 2017-06-09 at 6 55 08 pm](https://user-images.githubusercontent.com/52581/26964479-c07f3cee-4d45-11e7-8844-9e334b3fd5ad.png)

**Comment by cklosowski** [comment]
The plugin itself does very little styling. Per the advice of Sean. So really it's just you covering anything you want styled further. Looks like you hit all the cases.

**Comment by sumobi** [comment]
Sweet, thanks for the confirmation!

**Comment by pippinsplugins** [comment]
Looks great!
