### ISSUE TITLE
Image Position customizer controls display when no image loaded

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#152]
To replicate:

1. Add an image to the background image within the Customizer. Save it and come out of the customer.

2. Go back and remove the image, save it again.

3. Go back to the customizer and for some reason, the "Image Position" controls still display, even with no image in place. See screenshot:

![screenshot 2017-09-30 22 59 09](https://user-images.githubusercontent.com/22668877/31049812-38981b24-a633-11e7-9479-bb9f9513c1d1.png)

**Comment by amdrew** [comment]
@davidsherlock I don't see that behavior. Themedd doesn't touch the background image panel (apart from moving the color control out) so I have a feeling it's not related to Themedd. Does it happen also with the 2016 theme? Do you see any JS errors in your console? Does it happen with plugins deactivated? Try also clearing your JS cache and testing again. Let me know!

**Comment by davidsherlock** [comment]
Close this one off @amdrew, putting it down to a caching issues.
