### ISSUE TITLE
Improve 'select' design/appearance

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#153]
The select boxes at the minute stick out like a sore thumb, because of the rest of the form elements look sleek and unified with the minimal design.

Take this screenshot for example:

![screenshot 2017-10-01 13 08 16](https://user-images.githubusercontent.com/22668877/31054393-b89be8a2-a6a9-11e7-9343-521b32d8a8b1.png)

I feel since an SVG icon was introduced for the search box, it might be a good idea to do the same with the select boxes. Giving them the same height and appearance of the text fields, but with a small drop-down icon on the right-hand side to make them feel more connected to the other form fields.

**Comment by amdrew** [comment]
@davidsherlock Will look into it. I'd love the select menus to look similar to the other form elements..

**Comment by amdrew** [comment]
@davidsherlock Do you have any examples of pure CSS solutions for using SVGs with select menus that work on IE11? All other modern browsers should be ok.

**Comment by amdrew** [comment]
Not SVG but this is IE11 compatible: https://codepen.io/LucaRosaldi/pen/CjiKB

**Comment by davidsherlock** [comment]
It seems to depend on this meta tag being present: https://stackoverflow.com/questions/27494296/svg-not-showing-in-ie11

I will research further though and report here.

**Comment by davidsherlock** [comment]
@amdrew, experimented tonight with a pure CSS SVG solutions and came up with the following snippet:

```
select {
  padding: .8125rem;
  /* Required */
  border-radius: 0;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  /* SVG background image */
  background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='#696969'><polygon points='0,0 100,0 50,50'/></svg>") no-repeat;
  background-size: .7125rem;
  background-position: calc(100% - 1.1rem) center;
  background-repeat: no-repeat;
  background-color: #ffffff;
}

select:focus {
  outline: 0;
}
```

Which looks like this and is responsive and lightweight:

![screenshot 2017-11-01 02 51 09](https://user-images.githubusercontent.com/22668877/32257914-a8d761f8-beaf-11e7-85e1-659e7b724ab0.png)

Personally on the checkout, I feel a 100% width looks better for the selects to keep all the elements uniform.

Let me know your thoughts!

**Comment by davidsherlock** [comment]
To compensate for issues on the account/profile page, I recommend setting a default 100% width for the selects and removing the checkout select width rules. This will reduce CSS rules required and make the new selects work on all sections.

**Comment by davidsherlock** [comment]
Made some tweaks:

select {
    padding: .8125rem 2.2rem .8125rem .8125rem;
    border-radius: 0;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    background: url(data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='#696969'><polygon points='0,0 100,0 50,50'/></svg>) no-repeat;
    background-size: .7125rem;
    background-position: calc(100% - .8125rem) center;
    background-repeat: no-repeat;
    background-color: #ffffff;
}

**Comment by amdrew** [comment]
Awesome, will check it out and do some testing in different browsers.

**Comment by flowdee** [comment]
Would be awesome to get it added asap 👍

**Comment by davidsherlock** [comment]
These are the best SVG selects I have seen: https://pro.creativemarket.com/subscribe

Definitely worth copying that for Themedd!

**Comment by davidsherlock** [comment]
With the switch to Bootstrap 4 framework, this issue can be closed due to the in-built form element styling.
