### ISSUE TITLE
Wishlist model not showing on archive pages

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#17]
By default the EDD Wishlist plugin adds a button to the archive and single download page, however on the archive page clicking the button dosen't show the modal box and no javascript error is generated either. Here is what my page looks like this, no additional code or styling - just stock Themedd.

![screenshot 2017-06-13 12 48 46](https://user-images.githubusercontent.com/22668877/27081130-f1e065c6-5036-11e7-894a-c54affacec47.png)

**Comment by davidsherlock** [comment]
It's worth noting it works on the single download page.

**Comment by davidsherlock** [comment]
An additional (related) issue, the close icon isn't displaying on the wish list modal box.

![screenshot 2017-06-13 17 05 55](https://user-images.githubusercontent.com/22668877/27092364-ecc7edba-505a-11e7-90de-7f8d727da937.png)

**Comment by sumobi** [comment]
@davidsherlock Thanks, will check it out!

**Comment by amdrew** [comment]
Created some issues to cover these.
https://github.com/easydigitaldownloads/edd-wish-lists/issues/58
https://github.com/easydigitaldownloads/edd-wish-lists/issues/60
