### ISSUE TITLE
Remove Genericons dependency 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#175]
Within the stylesheet the `Genericons` are being loaded via inline CSS, causing a 200ms delay because the request can't fit into a single packet.

I'm not sure where the `Genericons` are being used on the theme or why they are loaded via CSS, but it might be worth dropping these references if possible to optimize the theme

**Comment by davidsherlock** [comment]
@amdrew, you could borrow the small SVG icon from the select CSS i posted:

```
select {
  padding: .8125rem 2.2rem .8125rem .8125rem;
  /* Required */
  border-radius: 0;
  -webkit-appearance: none;
  -moz-appearance: none;
  appearance: none;
  /* SVG background image */
  background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='100' height='100' fill='#696969'><polygon points='0,0 100,0 50,50'/></svg>") no-repeat;
  background-size: .7125rem;
  background-position: calc(100% - .8125rem) center;
  background-repeat: no-repeat;
  background-color: #ffffff;
}

select:focus {
  outline: 0;
}
```

**Comment by spencerfinnell** [comment]
Could also look at Dashicons which are bundled with WordPress. 

https://developer.wordpress.org/resource/dashicons/#exerpt-view

They can be loaded on the frontend too.

**Comment by davidsherlock** [comment]
@spencerfinnell, my only concern with that would be that it takes another request. My thinking right now is we convert the Genericons "icon" to inline SVG to reduce packet size and requests.

**Comment by amdrew** [comment]
@davidsherlock 👍 Issue for removing Genericons is here: https://github.com/easydigitaldownloads/themedd/issues/14
