### ISSUE TITLE
Add Sort By functionality to taxonomy and archive pages 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#176]
This is merely a suggestion and something that might be better suited to a 3rd party plugin.

Out with using FacetWP or another plugin, EDD contains now default sorting functionality. Sorting and filtering makes it a lot easier to find the products within your price range and/or popularity (sales, rating, etc.).

Potentially as part of Themedd, it would be nice to have the ability to "sort" the products like WooCommerce provides out the box. This was suggested for core prior, but was rejected for some reason.

**Comment by davidsherlock** [comment]
Close this one @amdrew, building a free plugin for this.

**Comment by SDavisMedia** [comment]
Definitely belongs in a plugin, if not EDD core. Definitely not one particular EDD theme.

Excited to see what you come up with!

**Comment by davidsherlock** [comment]
Agreed @SDavisMedia! Going to build a super simple plugin that replicates WooCommerce functionality and also a full AJAX version with filters (more than likely "Pro" version).

**Comment by amdrew** [comment]
Chur!
