### ISSUE TITLE
Affiliate register form style is not applied when user is logged in

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/themedd#178]
If you access to the affiliate area without login, forms are well styled

but accessing to this area logged in and not being an affiliate the form style is missing

The issue comes from the wrapper div with classes box and register that do not appear when just there is the register form

**Comment by amdrew** [comment]
@rubengc Are you using v1.0.4? I fixed that here: https://github.com/easydigitaldownloads/themedd/issues/170

**Comment by rubengc** [comment]
You are right! I have working with themedd 1.0.0
