### ISSUE TITLE
Checkout footer text not right aligned

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#18]
The subtotal, tax, discount, etc aren't right aligned on the checkout page.

![screenshot 2017-06-13 16 02 45](https://user-images.githubusercontent.com/22668877/27089321-f263cc8e-5051-11e7-8c3e-66b26ee41cbe.png)

**Comment by davidsherlock** [comment]
Similarly the "Save Cart" would be best right aligned.

**Comment by sumobi** [comment]
@davidsherlock Thanks, just realized also I haven't tested with various EDD settings on, oops :)
