### ISSUE TITLE
Theme updater script issue.

### ISSUE THREAD

**Issue by sachyya** [easydigitaldownloads/themedd#180]
I am using the theme updater script being used in this theme. But I found some errors on Theme updater, when I tried to add Invalid Licence for testing purpose. These are the errors seen during the test:

1. If invalid License put on the license field, this issues arise. 
`Undefined index: license-unknown in themedd\includes\updater\theme-updater-admin.php on line 375`

2. And if I save that invalid license and click activate button:
`Notice: Undefined property: stdClass::$site_count in themedd\includes\updater\theme-updater-admin.php on line 387`
`Notice: Undefined property: stdClass::$license_limit in themedd\includes\updater\theme-updater-admin.php on line 388`

**Comment by amdrew** [comment]
@sachyya I haven't been able to replicate those errors. Do you see them when you use Themedd as-is on your site (with invalid license etc), or are you only seeing them when you are using the updater script in your theme?

**Comment by sachyya** [comment]
Yes, these errors are produced while using Themedd theme. 

The issue arises when we put random license key in the Appearance->Themedd License->License Key input field.  Save it and click Activate License. 

Since these are just Notices, maybe in your dev environment you have turned it off for notices.

**Comment by amdrew** [comment]
My apologies @sachyya, I did indeed have `WP_DEBUG` set to false by accident. Will get those notices fixed, cheers!

**Comment by amdrew** [comment]
Fixed via https://github.com/easydigitaldownloads/themedd/commit/1016293297c2d6e0a5357dd26881ca00d441cd2d in release/1.0.5
