### ISSUE TITLE
Using plural form instead of singular form for zero items

### ISSUE THREAD

**Issue by fxbenard** [easydigitaldownloads/themedd#186]
Hi,

I spotted a funny behavior when the basket is empty;  it shows 0 item**s**

![2018-01-10_15-29-21](https://user-images.githubusercontent.com/802114/34777712-7b3ed4bc-f61b-11e7-886a-81ce1064774b.png)

**Comment by SDavisMedia** [comment]
Unless I'm misunderstanding what you are pointing out here, "0 items" is correct.

**Comment by fxbenard** [comment]
Closed! FYI adding a S is a mistake in many locales
