### ISSUE TITLE
FES field CSS issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#19]
Doing a quick audit of the Themedd theme and found a few issues with some field types.

Here are some screenshots for reference:

Avatar upload is messy:

![screenshot 2017-06-13 16 43 52](https://user-images.githubusercontent.com/22668877/27091953-a0391a4c-5059-11e7-837a-c4936c1b6f35.png)

New "Save Draft" button needs a right margin to separate it from the submit button.

![screenshot 2017-06-13 16 47 15](https://user-images.githubusercontent.com/22668877/27091963-a9595af6-5059-11e7-95cd-18b7b1547850.png)

This isn't a bug per say, but i can't help but feel the x (remove) button should overlay the image and show on hover to allow deletion. Failing that, a slightly larger link.

![screenshot 2017-06-13 16 47 33](https://user-images.githubusercontent.com/22668877/27092001-cfe7c4aa-5059-11e7-82e9-ab7b6b7ee303.png)

**Comment by sumobi** [comment]
@davidsherlock Nice, looks like I have lots more on FES to work on 👍

**Comment by davidsherlock** [comment]
To be fair it worked pretty well out of the box with the exception of the above field types! :)

**Comment by davidsherlock** [comment]
The announcement section on the dashboard could probably be better styled to appear more "announcement like" :)

<img width="1280" alt="screenshot 2017-06-14 00 30 06" src="https://user-images.githubusercontent.com/22668877/27109088-a87ea174-5098-11e7-9acf-a72023dba4a6.png">

**Comment by amdrew** [comment]
New avatar upload styling:

___

<img width="214" alt="screenshot 2017-06-19 12 14 08" src="https://user-images.githubusercontent.com/52581/27265390-d86c56c0-54e8-11e7-82e9-386c6557ccda.png">

___

<img width="239" alt="screenshot 2017-06-19 12 14 14" src="https://user-images.githubusercontent.com/52581/27265389-d866181e-54e8-11e7-96b5-e02aa6e74ad4.png">

___

<img width="233" alt="screenshot 2017-06-19 12 14 18" src="https://user-images.githubusercontent.com/52581/27265388-d864d71a-54e8-11e7-9952-94d2b8436a0b.png">

**Comment by amdrew** [comment]
Save draft button now has right margin

**Comment by amdrew** [comment]
> This isn't a bug per say, but i can't help but feel the x (remove) button should overlay the image and show on hover to allow deletion. Failing that, a slightly larger link.

Absolutely, this should be styled like the avatar upload above. Will hit that next.

**Comment by amdrew** [comment]
Featured image field now uses the same CSS as the upload avatar field.

<img width="967" alt="screenshot 2017-06-19 13 23 30" src="https://user-images.githubusercontent.com/52581/27266154-919af49a-54f2-11e7-9e2d-37f61725b008.png">
<img width="962" alt="screenshot 2017-06-19 13 23 43" src="https://user-images.githubusercontent.com/52581/27266155-91c0d8ea-54f2-11e7-9bf0-f768e74d67aa.png">
<img width="952" alt="screenshot 2017-06-19 13 23 48" src="https://user-images.githubusercontent.com/52581/27266156-91cb7c3c-54f2-11e7-9438-d319368e6343.png">

Will leave this issue open in case anything else is spotted.

**Comment by pippinsplugins** [comment]
Looks good!

**Comment by davidsherlock** [comment]
Yeah, this does look good - exactly how I imagined it should function!

I noticed one styling bug however with the Teeny Rich Editor, when you hover over the small icons the editor jumps around a lot due to the border width changes. See here:

![screenshot 2017-06-19 11 21 16](https://user-images.githubusercontent.com/22668877/27280949-c4d1f3ba-54e1-11e7-88e5-2f54b5a11f03.png)

**Comment by davidsherlock** [comment]
On that subject, the default height of the editor is pretty small as well:

![screenshot 2017-06-19 11 25 16](https://user-images.githubusercontent.com/22668877/27281037-20f51816-54e2-11e7-9ead-f5d00b7ec218.png)

**Comment by davidsherlock** [comment]
One other small fix (being a bit OCD here), but the width of the file upload field could be larger since the button dosen't occupy a lot of space in either state:

![screenshot 2017-06-19 11 30 42](https://user-images.githubusercontent.com/22668877/27281211-cc10c9d4-54e2-11e7-8252-aa6b2b0386b6.png)

**Comment by amdrew** [comment]
Made a note of the Teeny Rich textarea button issue here. Happens with Vendd and 2016 theme.
https://github.com/easydigitaldownloads/edd-fes/issues/1285#issuecomment-309683092

**Comment by amdrew** [comment]
@davidsherlock Looks like the height of the Teeny Rich Editor is intentional, it's like that on Vendd and 2016 also. There's a "rows" setting in the field type to set the height, however that only seems to affect the "normal" mode, not "Rich textarea" or "Teeny Rich textarea":

<img width="1087" alt="screenshot 2017-06-20 20 41 47" src="https://user-images.githubusercontent.com/52581/27324298-e6551018-55f8-11e7-8ea3-7ef71e63d90d.png">

At least the vendor can use the drag handle to resize the textarea. It seems to me however that setting the rows should affect all 3 types, will open an issue on FES repo.

**Comment by amdrew** [comment]
@davidsherlock The file upload buttons ("upload" and "choose file") will give more room to the input fields now:

<img width="962" alt="screenshot 2017-06-20 21 06 19" src="https://user-images.githubusercontent.com/52581/27325404-6f1954ce-55fc-11e7-963e-a02c95b5ae0d.png">

**Comment by davidsherlock** [comment]
I think this one can also be closed for now, since all the form elements are now styled for.
