### ISSUE TITLE
PHP notice on blog home when there are no posts

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/themedd#194]
When a site has no blog posts, the following notice shows up on the blog home:

`Notice: Trying to get property of non-object in /Applications/MAMP/htdocs/sandhills/wp-includes/comment-template.php on line 1196`

It's because the comments template is being called for no reason: https://github.com/easydigitaldownloads/themedd/blob/master/index.php#L39

Typically, that's not part of the index.php file. It was added here: https://github.com/easydigitaldownloads/themedd/commit/261b68c42cfcce86dad61737d2205c6f20ee53b0#diff-828e0013b8f3bc1bb22b4f57172b019d

I'm not seeing a reason to call the comments template tag from that template.

**Comment by cklosowski** [comment]
@amdrew is there a reason to call it or can we remove it?

**Comment by amdrew** [comment]
@cklosowski @SDavisMedia Oops, that can be removed!
