### ISSUE TITLE
Remove Schema.org microdata

### ISSUE THREAD

**Issue by sunnyratilal** [easydigitaldownloads/themedd#199]
JSON-LD has been added to EDD 3.0 (https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5240) and all microdata has been deprecated.  All references to the microdata should be removed from Themedd otherwise error notices will be displayed if `WP_DEBUG` is on.

**Comment by amdrew** [comment]
@sunnyratilal That's great news, thanks for the heads up

**Comment by amdrew** [comment]
Added the `themedd_edd_schema_microdata()` function back in. The current version of EDD still outputs microdata fluff so this still needs to be turned off for anyone using 2.x. 

I've tested with EDD 3.0 and can see that the `edd_add_schema_microdata` filter is now deprecated 👍. With the filter enabled and EDD 3.0, I still see the new `<script type="application/ld+json">` tags so everything is working as expected.
