### ISSUE TITLE
Earnings table double heading

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#20]
The "Commissions Overview" heading displays twice under the FES earnings tab, see screenshot for reference:

<img width="1255" alt="screenshot 2017-06-13 23 34 41" src="https://user-images.githubusercontent.com/22668877/27107648-1f6dab52-5091-11e7-893f-6278d51251f6.png">

**Comment by davidsherlock** [comment]
Similarly, the export earnings section could be cleaned up a bit!

<img width="1243" alt="screenshot 2017-06-13 23 40 08" src="https://user-images.githubusercontent.com/22668877/27107786-e29cbe2e-5091-11e7-92ec-9b54930f5151.png">

**Comment by amdrew** [comment]
Just replicated the duplicate heading with 2016 theme. It was just fixed in FES: https://github.com/easydigitaldownloads/edd-fes/issues/1276
