### ISSUE TITLE
Add basic Gutenberg support to Themedd

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#210]
Out of the box, the current build of Themedd supports Gutenberg almost entirely with a few notable exceptions such as the wide image support and some alignment issues on some elements.

While Themedd 1.1 is actively under development (and will support Gutenberg) via the move to Bootstrap, it's definitely a few months or more off so it might be worth revising the Gutenberg support in a more immediate point release (such as 1.0.7 or 1.0.8) since the release of WordPress 5.0 is planned for November I believe.

This is merely a suggestion, since I would say it's currently about 80% compatibility from what I can tell and it's going to prevent support requests when the Gutenberg switch happens.

**Comment by davidsherlock** [comment]
@amdrew please close this ticket, since we have discussed this via Twitter and the other independent issues cover the various areas needing improved.

**Comment by amdrew** [comment]
👍
