### ISSUE TITLE
Gutenberg: Add wide image support to Themedd

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#212]
While we discussed this and said it's optional for Theme developers, it's actually pretty straight forward to add to Themedd in the current build. The following is required (I have tested this - though it's a bit ghetto in relation to browser support, though a lot of major themes are using this approach):

I created two new CSS declarations:

```
.alignfull,
.alignwide {
    margin-bottom: 2em;
    width: 100%;
}

.alignfull,
.alignwide {
    width: 100vw;
    margin-left: 50%;
    transform: translateX(-50%);
}
```

Within the Themedd setup.php file, I added this line:

```
add_theme_support( 'align-wide' );
```

**Comment by davidsherlock** [comment]
Update: I ripped this from a well known for theme and while it needs a few things removed (duplicates), it pretty much adds full wide image support to the theme:

```
/*--------------------------------------------------------------
## Block Alignments
--------------------------------------------------------------*/
.wp-block-gallery {
  margin-left: 0;
  margin-bottom: 1.2em;
}

.wp-block-image figcaption {
  font-size: 15px;
  margin-top: 1em;
}

.entry-content .wp-block-gallery {
  padding-left: 0;
}

.alignfull,
.alignwide {
  margin-bottom: 2em;
  width: 100%;
}
@media (max-width: 600px) {
  .alignfull.wp-block-gallery,
  .alignwide.wp-block-gallery {
    margin-left: -8px;
    margin-right: -8px;
    width: inherit;
  }
}
.alignfull img,
.alignwide img {
  width: 100%;
  display: block;
}

.alignwide {
  max-width: none;
}
@media (min-width: 1000px) {
  .alignwide {
    width: 75vw;
    margin-left: calc( 50% - 75vw / 2 );
  }
}

.alignfull {
  width: 100vw;
  margin-left: calc( 50% - 50vw );
  max-width: none;
}

.wp-block-embed.wp-embed-aspect-16-9 .wp-block-embed__wrapper:before {
  padding-top: 0;
}

.wp-block-columns {
  margin-bottom: 1.2em;
}
```

**Comment by amdrew** [comment]
Thanks for the exploration! Anyone wanting to support wide images with the current version of Themedd will find the above helpful. 

As we discussed on Slack, v1.1 already supports wide images. There were quite a few changes made to implement wide image support (correctly IMO) without trying to break outside of the content area using negative margins which can cause quirks in some browsers.
