### ISSUE TITLE
Add full support for Bootstrap v4.1.3 utilities and components

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#215]
Based on the current Themedd 1.1 branch, it appears a lot of stuff is missing from the Bootstrap implementation such as Badges, Breadcrumb, Carousel, Dropdown, etc. The carousel specifically would be really useful to have for product galleries, but requires the some additional JS included with Bootstrap and of course the required utility CSS.

I feel Themedd 1.1 should really contain everything from Bootstrap v4.1.3, so child themes can easily utilise the lightweight functionality provided by the framework.

**Comment by amdrew** [comment]
Adding BS components to Themedd that it doesn't use just adds bloat to the CSS. Anything Themedd doesn't use will not be included for that reason. If a child theme wants to use BS's styling for carousels as an example, it can easily include that.
