### ISSUE TITLE
Revise the default cart icon quantity and total layout

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#217]
At the minute when showing quantity and total, the cart takes up a lot of real estate due to the fact "items" (or "item") is included in the string. While the layout can be modified easily in 1.1 using filters, most users won't be knowledgable about this.

Based on what you achieved with the SellBird theme, I believe if `quantity` is used it should be displayed like this in the secondary navigation menu:

<img width="149" alt="screenshot 2018-11-17 at 14 13 23" src="https://user-images.githubusercontent.com/22668877/48666375-176ea300-ea75-11e8-8705-2c55f33e08e3.png">

When the total is included also, it should show as a value at the side of this, which would reduce the real estate greatly and make the layout a lot more modern.

**Comment by amdrew** [comment]
I don't see any length-related issues with having `items` or `item` next to the cart icon. A user can hide/show the cart, hide/show the quantity text, and hide/show the total from the customizer, so there's complete control over how it is displayed. It's really up to the user as to how many items they put into the secondary menu (if they use it at all), and whether they enable the search bar. With everything active I think it looks fine:

<img width="1216" alt="screen shot 2018-11-19 at 3 57 57 pm" src="https://user-images.githubusercontent.com/52581/48683845-e8dafe80-ec13-11e8-9978-30074c6ede91.png">

It's also possible (via a filter) to change the labels entirely, for example `product` and `products`, or `book` and `books`. Changing the labels and/or layout can be documented easily enough for the 1.1 release.

While I think the referenced design looks nice, it can be implemented easily enough from a child theme (as it is), a code snippet, or a simple plugin. We could document this if need be in the form of a mini tutorial. 

As much as I would love to make it the "default" in Themedd, there would need to be a new custom color control added for the customizer and you lose the useful of the quantity text that has already been implemented. I prefer the simplicity of how it is now - anyone who wants to can swap it out for something fancier.

**Comment by davidsherlock** [comment]
I mainly opened this issue to start a discussion/dialog on the issue, I get what you are saying though. Close this one and it can be covered with a code snippet within Themedd.
