### ISSUE TITLE
Consider replacing default Bootstrap drop-down font icon with SVG

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#219]
While keeping true to the Bootstrap framework, I feel the SVG drop down arrow on the menu bar from the Twenty Seventeen theme looks a lot nicer than the current Bootstrap "icon".

This will feel cleaner and more modern in my opinion.

**Comment by amdrew** [comment]
The current icon used by BS is indeed an SVG (not a font). I've thought about replacing it with something a bit nicer 👍

**Comment by amdrew** [comment]
<img width="145" alt="screen shot 2018-11-19 at 3 37 49 pm" src="https://user-images.githubusercontent.com/52581/48683246-196d6900-ec11-11e8-932d-60dc85202893.png">

**Comment by amdrew** [comment]
See above for new icon.

**Comment by davidsherlock** [comment]
Love it! :)
