### ISSUE TITLE
Horizontal scroll for FES tables

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/themedd#228]
Unfortunately, we can't really depend on people to use Themedd's page templates for pages like the Vendor Dashboard. Vendd even has page templates that are super specific by name, and I see people not using those as well.

For the most part, this is on them. All of this is well-documented. However, in Themedd, you end up losing access to some functionality in FES table displays if the entire vendor dashboard is stuffed into the standard content width:

![Opera Snapshot_2019-05-20_135412_edd local](https://user-images.githubusercontent.com/2359131/58051378-dd0abf00-7b06-11e9-9d85-77df9b6aa170.png)

Notice the *Actions* column there. The *Date* column is hidden too, though that's a little less important. Without access to this column, vendors can't do things like edit an existing product submission.

Anything from available horizontal scroll to CSS or template tweaks would be good. I don't think the current state should be the default state, though.

**Comment by amdrew** [comment]
👍 to the proposed solution of showing the scrollbar when necessary. I'll add `overflow-x: auto;` to the `.fes-vendor-dashboard` div. Another solution would be to autoload the full width template but someone may actually want the widgets and sidebar to show. At least this way a user can either choose to use the full width template, or keep the existing layout and actually be able to get to the hidden columns.

<img width="1389" alt="Screen Shot 2019-05-21 at 2 31 22 PM" src="https://user-images.githubusercontent.com/52581/58064197-4a852100-7bd5-11e9-8d74-d08dac8f01f9.png">

**Comment by amdrew** [comment]
@SDavisMedia Can you please test this PR? https://github.com/easydigitaldownloads/themedd/pull/229

Will throw out a 1.0.7 release afterwards.

**Comment by SDavisMedia** [comment]
All good here. 👌
