### ISSUE TITLE
Reviews vendor feedback form/page needs styling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#23]
As per the title, here is the current output:

<img width="1214" alt="screenshot 2017-06-14 00 10 28" src="https://user-images.githubusercontent.com/22668877/27108577-f3fe675e-5095-11e7-9d61-6c1f214fca45.png">

**Comment by amdrew** [comment]
I see the same as you however this is what I see with the CSS disabled from the admin:
![screen shot 2017-06-27 at 8 22 17 pm](https://user-images.githubusercontent.com/52581/27577912-6c902ae6-5b76-11e7-9318-31ecc47ec47f.png)

It could be better but it's good enough until https://github.com/easydigitaldownloads/themedd/issues/64 is done.

**Comment by amdrew** [comment]
Heh, well apart from the 10 stars! That'll need to be fixed regardless.

**Comment by amdrew** [comment]
Once https://github.com/easydigitaldownloads/edd-reviews/issues/196 is merged this will look a lot nicer.
