### ISSUE TITLE
Pagination is causing warnings due to foreach issue.

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/themedd#230]
`PHP Warning:  Invalid argument supplied for foreach() in themedd/includes/compatibility/edd/actions.php on line 237`

**Comment by amdrew** [comment]
@cklosowski Downloads pagination I'm assuming? Will take a look.

**Comment by cklosowski** [comment]
Yeah i've got a PR incomign @amdrew

**Comment by cklosowski** [comment]
I'd like to get this fixed and on the EDD site ASAP. We've been having more and more complaints of errors on the site, and reducing the logs footprint is a good start.

**Comment by amdrew** [comment]
Sweet as 👍
