### ISSUE TITLE
Affiliate registration form from Affiliate Forms for Gravity Forms add-on not displaying

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#233]
When Affiliate Forms for Gravity Forms is active, the custom affiliate registration form isn't being shown. Instead, the standard form from AffiliateWP is being shown.

Related: https://github.com/AffiliateWP/affiliatewp-affiliate-forms-gravity-forms/issues/51

**Comment by amdrew** [comment]
PR: https://github.com/easydigitaldownloads/themedd/pull/234

@gspice Could you test that?

**Comment by amdrew** [comment]
Covered two scenarios:

1. Logged in/viewing the affiliate area
2. Logged out/viewing the affiliate area

In each instance, the AFGF form should be loaded into the left hand panel.

**Comment by gspice** [comment]
Works great!  Tested viewing logged in and also from a separate browser, registering for the first time.

I didn't realize this theme had the vertical tabs, snazzy!

<img width="1155" alt="Screen Shot 2019-07-09 at 13 23 30" src="https://user-images.githubusercontent.com/3018245/60920389-e84bb280-a24c-11e9-8b8e-447f87e83d0a.png">

**Comment by amdrew** [comment]
Great, cheers 👍
