### ISSUE TITLE
Improved download product title position

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#25]
At the minute the download product title shows on the side bar which dosen't make sense in the layout, and is too restrictive size wise for longer titles.

I recommend that the title is moved above the featured image so additional plugins like Subtitles (commonly used with EDD) are able to be used.

Currently looks like this to me:

![screenshot 2017-06-17 12 00 29](https://user-images.githubusercontent.com/22668877/27252387-225cd59c-5355-11e7-8c5e-6bdf8bc58f40.png)

**Comment by amdrew** [comment]
@davidsherlock I agree, I'll move the download title to the top area so that's the default layout (like I have done on RCP and AffWP anyway). It'll still be easy to move it to the side using a hook. 

In addition, a custom post type template can be included in the child theme (or another plugin) which could have the download title in the sidebar.

**Comment by amdrew** [comment]
Progress so far (subtitle added):

___

<img width="1588" alt="screenshot 2017-06-19 23 03 11" src="https://user-images.githubusercontent.com/52581/27282339-9fb96182-5543-11e7-8d47-3968eb586605.png">

___

And with some demo (ugly) colors for the page header to see how it would look:

<img width="1588" alt="screenshot 2017-06-19 23 03 22" src="https://user-images.githubusercontent.com/52581/27282338-9f9139e6-5543-11e7-985e-a66ebca638aa.png">

**Comment by davidsherlock** [comment]
haha I actually like this layout so far! Looking good and with enough space for larger product titles/subtitles. Are you going to add a customizer setting to set the title/header background colour as well?

Also is this the subtitles plugin or just post excerpts?

**Comment by davidsherlock** [comment]
Actually you will probably need a title/subtitle color option as well!

**Comment by davidsherlock** [comment]
I am going to open a separate issue about this, but the add to cart button on the sidebar would look a lot better with the price added to it like the Vendd theme does.

A big part of me wants to fork Vendd theme sidebar (and widgets) and plant it into Themedd :) haha

**Comment by amdrew** [comment]
> Are you going to add a customizer setting to set the title/header background colour as well?

The thought has crossed my mind but currently undecided. My initial thoughts were "Is this something a lot of people are going to use?" or could it be something people easily add with some CSS, if they wanted to. As you've pointed out, it would need color controls for the background color, heading and subtitle. Going to sit on it for a while.

> Also is this the subtitles plugin or just post excerpts?

Subtitles plugin

> I am going to open a separate issue about this, but the add to cart button on the sidebar would look a lot better with the price added to it like the Vendd theme does. A big part of me wants to fork Vendd theme sidebar (and widgets) and plant it into Themedd :) haha

Ok let me know when you've opened the issue and we can discuss there! Got a few ideas surrounding the download sidebar.

**Comment by amdrew** [comment]
Pushed up what I've done so far, see how that goes.
