### ISSUE TITLE
Commissions PayPal email address box styling required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#26]
The commissions PayPal email address box is missing styling on the account page.

![screenshot 2017-06-17 12 05 17](https://user-images.githubusercontent.com/22668877/27252452-ce56c41a-5356-11e7-9706-5c10da560e7c.png)

**Comment by davidsherlock** [comment]
You are just missing `#eddc_profile_paypal_fieldset` ID from the list of IDs.

**Comment by amdrew** [comment]
Good catch 👍
