### ISSUE TITLE
Grid list and Subpages templates

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#28]
The AffiliateWP theme includes these really useful page templates for building features pages based on either list or grid layouts. It would be useful to have these page templates included in Themedd core.

**Comment by amdrew** [comment]
They're handy but I won't be adding any additional page templates to Themedd. These can be adding via a child theme, custom plugin that inserts new page templates, or added as a "resource" to the Themedd site. Once you include page templates in the parent theme they will need to be supported by all child themes, or removed on a per-theme basis. It's also one more thing that a child theme needs will need to account for, not to mention the different interpretations of how such a page template should function.
