### ISSUE TITLE
Sectioned page template request

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#32]
Not trying to give you more work here @amdrew, just offering some useful suggestions (and of course some bug reports) for the theme/framework :) 

It would really useful to have a sectioned page template that used the associated child pages as "sections" with even/odd and child page name classes assigned.

**Comment by davidsherlock** [comment]
@amdrew, this is the type of page I mean: https://postpromoterpro.com/

**Comment by amdrew** [comment]
Similar to the reasons in https://github.com/easydigitaldownloads/themedd/issues/28 I don't see this belonging inside the theme. I'd love to see this in a child theme or on the site's resources section.
