### ISSUE TITLE
Terms of Agreement styling improvements

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#33]
I feel the Terms of Agreement on the checkout page could be improved somewhat by being boxed and a better more obvious, check out how it looks at present:

![screenshot 2017-06-17 21 34 38](https://user-images.githubusercontent.com/22668877/27256210-3c9cd5f0-53a6-11e7-9d5c-3abaf340c9ad.png)

**Comment by amdrew** [comment]
It doesn't exactly match the rest of the checkout does it, will do some tweaking.

**Comment by amdrew** [comment]
<img width="890" alt="screenshot 2017-06-21 17 02 30" src="https://user-images.githubusercontent.com/52581/27367897-760976cc-56a3-11e7-8954-46aac838d0e8.png">

**Comment by davidsherlock** [comment]
_Exactly_ what I had in mind - looks good!
