### ISSUE TITLE
Grid based article layout suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#36]
This is more than likely for a future release, but it would be cool to be able to switch the blog layout modes in the customizer to either being "classic" or "grid" based.

By grid based I mean like on AffiliateWP Blog: https://affiliatewp.com/blog/

Similarly the articles could be shown without a sidebar and in similar style to AffiliateWP.

**Comment by amdrew** [comment]
A grid layout would be neat, but better suited for a child theme.

> Similarly the articles could be shown without a sidebar and in similar style to AffiliateWP.

Removing the sidebar for single posts can be done with a filter already included in Themedd, or it could be provided via a custom post template placed in the child theme.
