### ISSUE TITLE
Footer 4 not usable/functional

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#37]
I believe this is due to the fact footer widget location 4 is removed via the code so the "meet our friends" section AffiliateWP and other sites have can be inserted manually. However in the context of the theme, adding widgets has no effect and may be confusing to users.

**Comment by amdrew** [comment]
Doh, footer 4 should work fine, will take a look. Thanks @davidsherlock !

**Comment by amdrew** [comment]
@davidsherlock Working for me, is there something in each footer widget section? Do you accidentally have code in your child theme (if using one) or a custom plugin that is affecting it?

<img width="1305" alt="screenshot 2017-06-19 11 20 37" src="https://user-images.githubusercontent.com/52581/27265024-640aa34c-54e1-11e7-98a2-c34c83b9dc4f.png">

**Comment by davidsherlock** [comment]
Apologies @amdrew, seems to be working now! Strange...

**Comment by amdrew** [comment]
No problemo! Let me know if it doesn't work again.
