### ISSUE TITLE
Single product archive page CSS layout issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#39]
With 3-6 items, the download output looks great but when only 1 product is published the output looks like this:

![screenshot 2017-06-19 11 04 39](https://user-images.githubusercontent.com/22668877/27280264-375b1ffe-54df-11e7-9235-d5f0d979145f.png)

With more products (for reference):

![screenshot 2017-06-19 11 04 11](https://user-images.githubusercontent.com/22668877/27280272-415568fc-54df-11e7-9e5a-c34d352c062e.png)

**Comment by davidsherlock** [comment]
Also happens with two products due to the flex layout widths:

![screenshot 2017-06-19 11 07 22](https://user-images.githubusercontent.com/22668877/27280357-8a637fac-54df-11e7-83ed-c4b827900cf2.png)

**Comment by amdrew** [comment]
@davidsherlock Can you please pull down the latest master and give it another shot?

**Comment by davidsherlock** [comment]
Fixed!

**Comment by amdrew** [comment]
Great! 👍
