### ISSUE TITLE
Integrate with EDD extensions

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#4]
Themedd should integrate with other popular EDD extensions. 
- [X] Commissions (well that was easy)
- [x] Wish Lists
- [x] Frontend Submissions
- [x] Reviews
- [x] Points and Rewards
- [x] Social Login
- [x] Recommended Products
- [x] Acquisition Survey
- [x] Recurring Payments
- [x] Software Licensing
- [x] Free Downloads
- [x] Cross-sell and Upsell

**Comment by pippinsplugins** [comment]
Definitely!

**Comment by sumobi** [comment]
Added the extensions from the marketplace bundle above

**Comment by pippinsplugins** [comment]
Added a few more to the list.

**Comment by sumobi** [comment]
Couple of screenshots of Recommended Products

Single download:

![screen shot 2017-03-21 at 5 43 05 pm](https://cloud.githubusercontent.com/assets/52581/24132929/f3b429a2-0e5d-11e7-8a48-e9bc2ce13934.png)

___

Checkout 
![screen shot 2017-03-21 at 5 42 49 pm](https://cloud.githubusercontent.com/assets/52581/24132930/f3dd677c-0e5d-11e7-8379-8d0bf07a8b1c.png)

**Comment by sumobi** [comment]
Points and rewards:

single download:

![screen shot 2017-03-22 at 6 54 40 pm](https://cloud.githubusercontent.com/assets/52581/24184089/14b4ea64-0f31-11e7-82ce-99b1118ac1d1.png)

points history:

![screen shot 2017-03-22 at 6 55 27 pm](https://cloud.githubusercontent.com/assets/52581/24184113/32b899ca-0f31-11e7-901d-5bb848a662c2.png)

**Comment by sumobi** [comment]
Only FES remaining.

**Comment by sumobi** [comment]
Points and rewards - checkout:

![screen shot 2017-03-22 at 11 04 14 pm](https://cloud.githubusercontent.com/assets/52581/24192457/f0397dc6-0f53-11e7-91d1-2d26f422f972.png)

**Comment by pippinsplugins** [comment]
This is looking great!

**Comment by sumobi** [comment]
Some FES screenshots:

![screen shot 2017-03-26 at 5 27 43 pm](https://cloud.githubusercontent.com/assets/52581/24328588/c97a3894-1249-11e7-9282-ee17fe46a795.png)

![screen shot 2017-03-26 at 5 27 58 pm](https://cloud.githubusercontent.com/assets/52581/24328587/c9773f68-1249-11e7-8632-c12ab1d5bec9.png)

![screen shot 2017-03-26 at 5 28 13 pm](https://cloud.githubusercontent.com/assets/52581/24328585/c97280cc-1249-11e7-8d62-5b4c2df87e20.png)

![screen shot 2017-03-26 at 5 28 24 pm](https://cloud.githubusercontent.com/assets/52581/24328586/c974a0f0-1249-11e7-8068-bf6afd1f9664.png)

![screen shot 2017-03-26 at 5 28 33 pm](https://cloud.githubusercontent.com/assets/52581/24328584/c9703f9c-1249-11e7-8c94-7bfadf112777.png)

![screen shot 2017-03-26 at 5 28 39 pm](https://cloud.githubusercontent.com/assets/52581/24328583/c96f2d8c-1249-11e7-8e65-716428c88cfa.png)

**Comment by pippinsplugins** [comment]
Looking great!

**Comment by sumobi** [comment]
Marking as closed, I'm sure I've missed something but that will be revealed in testing

**Comment by davidsherlock** [comment]
@sumobi, did some testing today with FES and the look you present in the screenshots dosen't appear to be showing for me (the tabs and borders are missing). I am using the latest branch of FES from GitHub.

![screenshot 2017-06-13 16 11 03](https://user-images.githubusercontent.com/22668877/27089776-4ab95092-5053-11e7-8460-ea012ecbf769.png)

**Comment by sumobi** [comment]
@davidsherlock Thanks for spotting!

**Comment by davidsherlock** [comment]
Happy to help @sumobi, keen to build some child themes for it! Curiously do you have any idea when the first version will be (officially) released?

I'll keep testing out the extensions to make sure everything works "out of the box" as expected.

I believe the issues above are related to the recent FES styling updates.

**Comment by sumobi** [comment]
Don't have an _exact_ date but I'm currently full steam ahead to get it out the door as soon as possible.

**Comment by davidsherlock** [comment]
@sumobi, just a quick heads up - it won't annoy you too much if i post issues I find here (even small CSS ones)? not trying to give you more work (or be a pain in the butt), but would be good to get all the base EDD plugins covered out of the box! :)

**Comment by sumobi** [comment]
It won't annoy me at all, please do! Easy to miss the little (or big) things.

**Comment by davidsherlock** [comment]
@sumobi, one thing to note is the FES styling for the registration/login shortcodes has been updated which might need to be fixed in your theme (still testing!).

**Comment by davidsherlock** [comment]
@sumobi, noticed something missing from Commissions styling...

<img width="868" alt="screenshot 2017-06-14 00 25 17" src="https://user-images.githubusercontent.com/22668877/27109006-25bdd520-5098-11e7-8e43-c86a21bf675b.png">

**Comment by davidsherlock** [comment]
@amdrew, on mobile views the current FES menu isn't easy to use/navigate since it's just links basically. 

Here is what I see at present:

![2017-06-19 11 52 01](https://user-images.githubusercontent.com/22668877/27284443-a84c0168-54f0-11e7-9453-b98cd8de755e.png)

I recommend a layout like this for mobile devices (taken from my Vendd child theme):

![screenshot 2017-06-19 13 06 12](https://user-images.githubusercontent.com/22668877/27284448-b581806a-54f0-11e7-91e3-e53a32b1b0d8.png)

**Comment by amdrew** [comment]
Opened a new issue for the above
