### ISSUE TITLE
Incorporate price into purchase button

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#44]
Much like Vendd, it would look better to have the price within the purchase button and for variable priced products it would simply say "Purchase" and resort to the default option (or goto the product page so they could pick specific options). 

Free Downloads would just say "Free Download" or similar. This would free up a fair bit of screen real-estate, since the price tag wouldn't be taking up space.

**Comment by davidsherlock** [comment]
I actually wrote this function to get the price ranges for variable priced products:

```
/**
 * Custom EDD Price Range
 */
function vendd_edd_price_range( $download_id = 0 ) {

	$low   = edd_get_lowest_price_option( $download_id );
	$high  = edd_get_highest_price_option( $download_id );
	$range = '<span class="edd_price">' . edd_currency_filter( edd_format_amount( $low ) );
	$range .= ' – ';
	$range .= edd_currency_filter( edd_format_amount( $high ) ) . '</span>';

	return apply_filters( 'edd_price_range', $range, $download_id, $low, $high );
}
```

**Comment by amdrew** [comment]
There's now a filter to move the price inside the button (as per the other issue). 

I'm not a fan of removing the variable pricing options and having a purchase button that adds the default price option to the cart, but a "view options" button or similar could work. Something for the child theme though. 

With the introduction of download meta in https://github.com/easydigitaldownloads/themedd/issues/58, the theme could enable the price which would show a `From $50` for variable priced options. This can optionally be linked through to the single download page. You could also easily replace that with a `$10 - 50` type price as per the code snippet above.
