### ISSUE TITLE
Better subtitles support

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#46]
There's a few instances where subtitles (from the subtitles plugin) are being shown in the download grid etc. These should really only be shown on the single download page.

**Comment by davidsherlock** [comment]
@amdrew, I actually posted a bug report for the Recommended Products plugin in relation to subtitle support. Posted it here: https://github.com/easydigitaldownloads/edd-recommended-products/issues/45

**Comment by amdrew** [comment]
^ That should take care of it. Only allowing subtitles within the `themedd_page_header()` function, which is outputted everywhere where you see those main page headers (pages, single posts, single downloads etc).

Going to leave this open for a bit incase for some reason I spot one where it shouldn't be.

**Comment by davidsherlock** [comment]
Seems to have fixed the issues @amdrew, nice work!
