### ISSUE TITLE
Disable background image on full-width layout mode

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#51]
When the full-width layout mode is enabled the background image should be disabled on the front-end. On the same note, a short description under the background image should be included informing users that it won't be rendered on full screen layout mode.

The reason for reporting this issue was due to the fact the background image occasionally 'peeks' through on full-width layout mode near the footer section.

**Comment by amdrew** [comment]
@davidsherlock Can you show me a screenshot of the background showing near the footer? Should be able to fix that. It's possible the user may actually want a background image _and_ a full-width layout so I don't think it should be automatically disabled.

A good (and crude) example might be something like the following, where the layout is full-width but the user has modified the CSS to show some parts of the background:

<img width="2371" alt="screenshot 2017-06-22 13 14 59" src="https://user-images.githubusercontent.com/52581/27412999-d00c940c-574c-11e7-9c77-92aef73df7db.png">

**Comment by davidsherlock** [comment]
@amdrew, you can see the issue at the bottom of the screenshot. Made the background blue so it was obvious to see the issue :) 

![screenshot 2017-06-28 22 52 16](https://user-images.githubusercontent.com/22668877/27662186-b9fd5b30-5c54-11e7-8709-23ae445f4ca7.png)

**Comment by amdrew** [comment]
Thanks! will check it out

**Comment by amdrew** [comment]
@davidsherlock I've managed to replicate this issue, but only on FES-related pages like the dashboard (as per your screenshot). Can you note the pages it appears on? And if you deactivate the FES plugin and refresh, does it go away?

**Comment by davidsherlock** [comment]
@amdrew, for some reason I am not seeing this issue anymore. I suggest closing this issue and we can re-open it if it re-appears.
