### ISSUE TITLE
Review breakdown styling suggestions

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#53]
This is probably better suited to the reviews repo, but the way the reviews breakdown displays is pretty out of place in the grand scheme of things. It would be better if this used percentages and was in turn responsive.

![screenshot 2017-06-21 10 55 20](https://user-images.githubusercontent.com/22668877/27378875-24b74290-5671-11e7-86a3-12d683872d52.png)

Posting here because we are overriding the default stylesheets.

**Comment by amdrew** [comment]
👍 Will be doing a full re-write of the reviews CSS for Themedd. I do think the default styling for reviews needs a smidgen of work as shown in the image above.

**Comment by davidsherlock** [comment]
Good call! I think something like this would look good for the actual reviews display:

![screenshot 2017-06-21 12 14 40](https://user-images.githubusercontent.com/22668877/27381621-6f6b0f9c-567b-11e7-9e14-442fea8dc95c.png)

**Comment by davidsherlock** [comment]
Think this one can be closed off @amdrew, since you restyled the reviews plugin (including the breakdown section).

**Comment by amdrew** [comment]
👍
