### ISSUE TITLE
Selects missing border CSS styling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#54]
The selects within the theme are missing `border: 1px solid #e5e5e5;` resulting in them having a black border by default which looks out of place compared with other fields.

**Comment by amdrew** [comment]
Screenshot? Usually if you add a border if drastically changes the select menu. Keeping borders etc off makes sure the select menu is rendered the way the operating system intended.

Example:

default checkout select menus in MacOS

<img width="439" alt="screenshot 2017-06-21 22 11 48" src="https://user-images.githubusercontent.com/52581/27379246-ac26bc80-56ce-11e7-9591-1d57f7c0f860.png">

And after adding a 1px border:

<img width="438" alt="screenshot 2017-06-21 22 11 42" src="https://user-images.githubusercontent.com/52581/27379260-b661c9ec-56ce-11e7-91e6-170d9e1116ac.png">

**Comment by davidsherlock** [comment]
![screenshot 2017-06-21 11 16 58](https://user-images.githubusercontent.com/22668877/27379453-337c80ea-5673-11e7-9f22-47c03f20728c.png)

![screenshot 2017-06-21 11 17 04](https://user-images.githubusercontent.com/22668877/27379455-34d440d6-5673-11e7-93cb-f61804c373be.png)

On MacOS as well, using Google Chrome! Here is with the border set as suggested:

![screenshot 2017-06-21 11 18 50](https://user-images.githubusercontent.com/22668877/27379514-6b990714-5673-11e7-8758-e3e71d937e41.png)

![screenshot 2017-06-21 11 18 45](https://user-images.githubusercontent.com/22668877/27379521-71ebae0a-5673-11e7-97b7-9361d8928add.png)

**Comment by amdrew** [comment]
Ahh I was using Firefox earlier. Ok let's add the border. Firefox users already see WP core with the FF select menus styles. Here's an example:

<img width="398" alt="screenshot 2017-06-21 22 25 23" src="https://user-images.githubusercontent.com/52581/27379745-9cb265d6-56d0-11e7-8f94-b1adc986e200.png">

**Comment by amdrew** [comment]
Added a 2px border to be consistent. It's hardly noticeable though. Look ok on your end?

**Comment by davidsherlock** [comment]
Looking good here @amdrew!

**Comment by amdrew** [comment]
Excellent, closing.
