### ISSUE TITLE
Show author on download grid

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#58]
Similarly to the Vendd theme, the download author should be shown on the download grid when FES is active. It should also be shown when a filter is set to true, so themes not using FES can still show an author.

When FES is activated it will show the store name, and link through to the vendor's shop page.

**Comment by amdrew** [comment]
Themedd now supports "download meta" in the download grid. This consists of the Author, author avatar, and price (off by default).

By default the download meta will show below the download title when FES is activated. You can also as originally mentioned above, show the download meta on themes not using FES, by enabling the filter.

![screen shot 2017-06-26 at 7 59 19 pm](https://user-images.githubusercontent.com/52581/27529802-047df6bc-5aaa-11e7-8d8f-1a628424bd47.png)

With a filter you can quickly move it to the very bottom of the download:
![screen shot 2017-06-26 at 8 01 21 pm](https://user-images.githubusercontent.com/52581/27529872-4d7272b2-5aaa-11e7-9564-0d44e5c30b7f.png)

And show the download's price:

![screen shot 2017-06-26 at 8 03 01 pm](https://user-images.githubusercontent.com/52581/27529938-881c0022-5aaa-11e7-8503-760dff4eedaa.png)

There's a few other things you can do such as hide the author's name, make the avatar any size, link the price through to the download, change `by` to something else etc:

![screen shot 2017-06-26 at 8 06 33 pm](https://user-images.githubusercontent.com/52581/27530053-03037f0e-5aab-11e7-8343-f7a30c3eb511.png)

![screen shot 2017-06-26 at 8 13 34 pm](https://user-images.githubusercontent.com/52581/27530259-fe44dbb0-5aab-11e7-9860-7d74b35c395f.png)

Will leave this open in case any one spots an issue, otherwise I think this is good to go.

**Comment by davidsherlock** [comment]
@amdrew, to save me searching the code base - could you post snippets of code you used to achieve each of these looks? Keen to try them out and give them a test run!

**Comment by davidsherlock** [comment]
I would also suggest adding the following:

1. The ability to have the vendor name/avatar above the title (as per Vendd)
2. If the avatar only is shown, the tooltip should be the store name or display name if not set.

**Comment by amdrew** [comment]
@davidsherlock 

Play around with this to achieve the various layouts

``` php

function themedd_child_edd_download_meta_options( $options ) {

	$options['price']       = false;
	$options['price_link']  = true;
	$options['author_name'] = true;
	$options['author_link'] = true;
	$options['author_by']   = 'From';
	$options['avatar']      = true;
	$options['avatar_size'] = 32;

	return $options;
}
add_filter( 'themedd_edd_download_meta_options', 'themedd_child_edd_download_meta_options' );

```

And to move the download meta position

``` php
function themedd_child_edd_download_meta_position() {
	return 'after';
}
add_filter( 'themedd_edd_download_meta_position', 'themedd_child_edd_download_meta_position' );
```

> The ability to have the vendor name/avatar above the title (as per Vendd)

Will see how it looks.

> If the avatar only is shown, the tooltip should be the store name or display name if not set.

Do you mean the title attribute of the link, the alt tag of the image, or both? I'll rig the alt tag of the image to be the store or author's name (if no FES).

**Comment by amdrew** [comment]
Ok there's now one more position for the download meta, just before the title. In the example above, change `after` to `before_title`.

**Comment by davidsherlock** [comment]
@amdrew, quick question - how do I show the price inside the purchase button?

**Comment by davidsherlock** [comment]
Also one more question, if variable pricing descriptions are enabled how do I remove them from showing on the archive page?

**Comment by davidsherlock** [comment]
There is a slight issue with the categories/tags taxonomy pages displaying the price twice and not honouring the "buy button". See screenshot:

![screenshot 2017-06-27 11 50 38](https://user-images.githubusercontent.com/22668877/27584195-ffc141e4-5b2e-11e7-9bd7-00696c9d4a58.png)

The prices displays twice and the purchase/buy button isn't being shown as per the default behaviour.

**Comment by amdrew** [comment]
> There is a slight issue with the categories/tags taxonomy pages displaying the price twice and not honouring the "buy button".

Looks like the above was handled in https://github.com/easydigitaldownloads/themedd/issues/71

> quick question - how do I show the price inside the purchase button?

``` php
function themedd_edd_price_outside_button() {
	return false;
}
add_filter( 'themedd_edd_price_outside_button', 'themedd_edd_price_outside_button' );
```

Note, filter name may change

> Also one more question, if variable pricing descriptions are enabled how do I remove them from showing on the archive page?

By editing the download grid template part. Also, https://github.com/easydigitaldownloads/themedd/issues/73 will help
