### ISSUE TITLE
Wishlist styling issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#60]
When the "Display Tax Rate on Prices" is enabled in EDD, it messes up the wish list display, see here:

<img width="1290" alt="screenshot 2017-06-26 13 44 07" src="https://user-images.githubusercontent.com/22668877/27539820-ddde1426-5a75-11e7-9b98-ab9c85818f1b.png">

**Comment by davidsherlock** [comment]
On that note, the actual "Edit" text is a bit small and would probably look better like a button as per the other areas of Wish lists.

<img width="1298" alt="screenshot 2017-06-26 13 59 22" src="https://user-images.githubusercontent.com/22668877/27540335-be1a1a0c-5a77-11e7-94f2-24e788a52f47.png">

**Comment by amdrew** [comment]
I'll investigate the first issue. The second issue can fall under https://github.com/easydigitaldownloads/themedd/issues/35

**Comment by amdrew** [comment]
@davidsherlock Can't seem to replicate, this is what I see:
![screen shot 2017-06-27 at 1 14 05 pm](https://user-images.githubusercontent.com/52581/27566628-93fa96ca-5b3a-11e7-997a-5caecb4be032.png)

Is there anything special about that first free download you have?

**Comment by amdrew** [comment]
Closing, let me know if you spot the issue.
