### ISSUE TITLE
Improved styling for EDD Reviews

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#64]
Like Wish Lists (https://github.com/easydigitaldownloads/themedd/issues/35) I'm planning on doing a full rewrite of the CSS from the EDD Reviews extension to make it perfectly blend into Themedd.

**Comment by amdrew** [comment]
^ First pass.

See https://github.com/easydigitaldownloads/edd-reviews/issues/created_by/amdrew.

**Comment by davidsherlock** [comment]
Nice work @amdrew, only thing missing is reviews pagination styling:

<img width="858" alt="screenshot 2017-07-05 16 28 11" src="https://user-images.githubusercontent.com/22668877/27871989-4719b3c0-619f-11e7-840d-706c4e84fec9.png">

**Comment by amdrew** [comment]
@davidsherlock Good spotting, try that ^

So many plugins have pagination that needs to be styled, but they all use different class names. Will hopefully come up with a way to standardize them all.
