### ISSUE TITLE
If vendor avatar image has been manually deleted don't display it or use a placeholder

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#65]
I was doing some testing with images and noticed that when the vendor avatar is manually deleted from the media library it shows empty on the product grid (and various other locations), messing up the layout. It might be a good idea at theme level to check it exists before displaying it.

**Comment by amdrew** [comment]
@davidsherlock Can you provide some screenshots and steps to replicate the issue? 

I added a user avatar field to the vendor's profile, selected an image as the vendor, and then deleted it from the media library but I still see the avatar on the download grid:

![screen shot 2017-06-29 at 3 36 34 pm](https://user-images.githubusercontent.com/52581/27670435-f6afe8ae-5ce0-11e7-98d3-85efe958e0f6.png)

**Comment by davidsherlock** [comment]
I should have been clearer, I mean manually deleting using FTP or similar.

**Comment by amdrew** [comment]
@davidsherlock Gotcha. You'll see the same thing when you delete a download image or even an image from a post. Can't think of any way to solve but open to suggestions!
