### ISSUE TITLE
Some customizer color settings not displaying in real-time within live preview

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#66]
I haven't tested every setting, but settings such as the sub menu colours and alike don't update within the live preview. From what I can tell it's mainly sub/menu related.

**Comment by amdrew** [comment]
Will check it out

**Comment by amdrew** [comment]
Closing in favor of https://github.com/easydigitaldownloads/themedd/issues/88. 99% sure it's related.
