### ISSUE TITLE
Frontend Submissions <a> tags not being styled by customizer setting

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#67]
The <a> links in FES aren't being styled for by the customizer link colour. I actually found a few other places similar things were happening, but my memory has went blank at the minute! Will report them when I find them :)

**Comment by amdrew** [comment]
👍

**Comment by amdrew** [comment]
@davidsherlock Can't seem to replicate this, are you still seeing this issue?

**Comment by davidsherlock** [comment]
@amdrew, can't seem to replicate again - I believe this issue is now resolved. The issue can be closed.
