### ISSUE TITLE
Reviews plugin pagination styling required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#68]
The reviews plugin is missing pagination styling. The pagination is actually missing a wrap which I reported on the repo.

**Comment by SDavisMedia** [comment]
I closed the issue you opened on Reviews as I've already taken care of it for Reviews 2.1. https://github.com/easydigitaldownloads/edd-reviews/issues/184

**Comment by davidsherlock** [comment]
Thanks Sean!

**Comment by amdrew** [comment]
@davidsherlock https://github.com/easydigitaldownloads/themedd/issues/64#issuecomment-313608844 Should take care of this but let me know if that's not the case.

**Comment by davidsherlock** [comment]
Still the same as before @amdrew...

![screenshot 2017-07-07 11 32 11](https://user-images.githubusercontent.com/22668877/27954442-ee8c54d2-6307-11e7-993c-b4158729ec2a.png)

**Comment by amdrew** [comment]
@davidsherlock Can you try clearing your browser cache? This is on a single download page, correct? 

<img width="1164" alt="screenshot 2017-07-07 23 58 29" src="https://user-images.githubusercontent.com/52581/27956979-48dab0e2-6370-11e7-9935-d935b66fc9d3.png">
