### ISSUE TITLE
Default (no widgets) download sidebar hooks required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#69]
If possible can someone hooks be added to the default download sidebar below each of the widgets to allow new sections to be inserted easily? At the minute only start and end points exist, but it would be great to have some in between each widget allow easy insertion.

**Comment by amdrew** [comment]
👍  Sure can

**Comment by amdrew** [comment]
themedd_sidebar_download_product_details_after
themedd_sidebar_download_author_after
