### ISSUE TITLE
Add theme updater

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#7]
We'll eventually need a theme updater class since updates will be served from the EDD site

**Comment by sumobi** [comment]
Or hosted on WordPress.org? Hrmm...

**Comment by pippinsplugins** [comment]
I vote for self-hosting, simply due to the excessively long review times on
.org.

**Comment by spencerfinnell** [comment]
You could submit it to .org with the same slug and when it eventually gets approved transition over to those updates (since it will still check for them if the slug matches)
