### ISSUE TITLE
Add author display_name to FES vendor page

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#74]
As per the issue title, it would be good to have the author display name (not store name, as that's displayed at the top of the page) under the avatar. 

This makes sense, because you are technically contacting the owner of the "store" and it's nice to refer to them on more personal terms.

**Comment by amdrew** [comment]
👍 Will add it

**Comment by amdrew** [comment]
@davidsherlock How's that look

**Comment by davidsherlock** [comment]
Yep, exactly that! Nice one.

**Comment by amdrew** [comment]
Sweet!
