### ISSUE TITLE
Additional customizer color settings

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#75]
It would be useful to have the following (additional) customizer color settings:

- Ability to set the content area background color (for example to create dark sites).
- Text colour, in-line with the above to allow support for dark color schemes (for example allowing white text).

Think that's all for now, since the other areas are already taken care of.

**Comment by rubengc** [comment]
+1 for content background, first need I found on install themedd

**Comment by amdrew** [comment]
@davidsherlock @rubengc 

It would be useful, however by adding the background and text color controls, it will be expected that other color controls be introduced. Some quick examples:

- heading color (dark grey at the moment)
- date color (that appear above headings)
- blockquote color (for the border next to blockquotes)
- inserted text background color
- table TH background colors
- table border colors
+ many more

Not to mention the plugins that Themedd currently supports, which sometimes add their own elements which will need color controls. The header and footer section are areas where plugins don't (generally) touch so it's safe to add color controls for them. 

Based on the above, I see it quickly snowballing out of control and not something I see being added at this point. Sure, there will be those that would like a dark colored site but I think this is best left to a child theme, or left to the user to do themselves.

Interested to hear your thoughts!

**Comment by davidsherlock** [comment]
My suggestion would be to keep it simple and add only the 'core' elements, the additions would be:

- Header color
- Text color
- Content background color

The rest of stuff should be handled by child themes, as it's more design specific.

**Comment by amdrew** [comment]
@davidsherlock That sounds like it could work but the reality of it is the customer will open up a support ticket the instant they realize there are more elements they can't change the color for, such as those listed above. It would feel "broken" or "incomplete" to the customer if the theme provided some of the colors, but not the rest.

The child theme should add all the color options required for a dark theme, or the customer should add all the required colors themselves through CSS.

**Comment by davidsherlock** [comment]
Andrew, I'm fine with adding it to the child theme.

Curiously what's the best way to override the customiser, colour defaults via a child theme? Which method is best employed?

**Comment by rubengc** [comment]
Hey @amdrew as features test environment we could setup a plugin with those additional features (colors, fonts, hero at home) and we can decide if finally it becomes to be a feature on themeed

What do you think?

**Comment by amdrew** [comment]
@davidsherlock I'll probably need to make some tweaks but the best way will be to simply filter the default colors (filter not yet available) from your child theme. I'll let you know when that's possible.

**Comment by amdrew** [comment]
@rubengc I don't quite understand your question. Are you saying you'd like to first make a plugin to add fonts, additional colors + hero image functionality, and then later merge them into Themedd? If so, these aren't things that will be live in the base theme. 

Additional colors (like the ones described above) can be added from the child theme. There may be other color settings added in the future but it really depends on what they are and if they are absolutely necessary.

Fonts aren't something that will be included by default. That will be up to the user to add via a tutorial, via a free add-on (perhaps), or from the child theme.

Likewise, a hero image on the homepage is nice but best kept to the child theme (or plugin) since not all themes will require it. It won't include any slider plugins either.

**Comment by rubengc** [comment]
You should keep in mind the hero feature (just with a background color, background image, main text and secondary text settings)

Is one of the most common needs, just checking edd, affiliatewp and post promoter pro sites anyone will see they are using a hero element at homepage

About the plugin, I mean something as a dev tools or code snippets library where you can be more flexible on accept contributions and use It to check what are the most used features to add to themedd

**Comment by amdrew** [comment]
@davidsherlock See #87

**Comment by amdrew** [comment]
@rubengc Absolutely, it's a common thing to do (as I did on the site above), however it's not something _everyone_ will want. Themedd is geared more towards a "starting point" so it's better not to include everything and leave it to the child theme/code snippet/plugin to implement such functionality.

If it was included in the parent theme, all child themes (if any) now need to support it and it becomes _expected_. If a child theme decides not to include it, more code now needs to be added to remove it. Not to mention all the various ways such a feature could be implemented.

> About the plugin, I mean something as a dev tools or code snippets library where you can be more flexible on accept contributions and use It to check what are the most used features to add to themedd

👍 Was planning on reviewing any contributions here: https://github.com/easydigitaldownloads/themedd-code-snippet-library

**Comment by davidsherlock** [comment]
@amdrew, close this one off - taking care of it via my child theme.

**Comment by amdrew** [comment]
👍
