### ISSUE TITLE
Improve commissions export styling

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#76]
Pretty simple one, but the commissions export styling and selects are a bit messy. Check here:

![screenshot 2017-07-01 20 49 37](https://user-images.githubusercontent.com/22668877/27764991-e5494988-5e9e-11e7-87af-48b0fffc0f89.png)

**Comment by amdrew** [comment]
@davidsherlock Is this on the `Earnings` tab of the vendor dashboard? Here's what mine looks like:

<img width="396" alt="screenshot 2017-07-02 23 22 28" src="https://user-images.githubusercontent.com/52581/27769453-6c2f1d18-5f7d-11e7-8a95-2ccb65afce75.png">

Are you on latest master? Can you try clearing your browser cache?

**Comment by davidsherlock** [comment]
Close this @amdrew, was being stupid and forget I was applying select styling via Javascript!

This is a bit cheeky however, but would you be able to add an additional selector to the button class for:

`#edd_orders_export .button`

I've wrote a free FES vendor order exporter plugin that integrates with commissions, shipping, etc and will be uploading it tonight to WordPress.org! The rest of the styles/classes it uses are identical to the commissions export hence the request :)

**Comment by amdrew** [comment]
No worries!

> This is a bit cheeky however, but would you be able to add an additional selector to the button class for:

Are you wanting to add a new class to the "Download CSV" button? If so, that's coming from the commissions plugin and not something Themedd has control over.

**Comment by davidsherlock** [comment]
Sorry @amdrew, should have been clearer. You have the following styling in the theme:

```
#edd_commissions_export .button {
    font-size: 0.875rem;
    padding: 0.25rem 0.75rem;
}
```

I need the following:

```
#edd_commissions_export .button,
#edd_orders_export .button {
    font-size: 0.875rem;
    padding: 0.25rem 0.75rem;
}
```

**Comment by amdrew** [comment]
@davidsherlock Ahh I see. I take it your new section appears on the same "level" as the other tables? If so, how about we rename the selector to `#edd_user_commissions .button` and that way, your new section, the export section, and any new buttons (I can't see that happening but you never know) will get the same styling.

**Comment by amdrew** [comment]
Try that ^

**Comment by davidsherlock** [comment]
@amdrew, I actually just released the plugin on WordPress.org if you want to check it out: https://wordpress.org/plugins/edd-vendor-order-exporter/

I wanted to avoid selector reuse since it would be a duplicate ID. So gave my exporter a unique ID (`#edd_orders_export`).

**Comment by amdrew** [comment]
@davidsherlock Is the exporter div included within the parent `#edd_user_commissions` div like the other tables? If so, then the button should be styled fine.

**Comment by davidsherlock** [comment]
@amdrew, the plugin is unrelated to commissions since it appears on the "Orders" page within Frontend Submissions. It's not a problem to add the required stylings to my child theme, just let me know either way!

**Comment by amdrew** [comment]
@davidsherlock Ahh, not related to commissions, gotcha. I've installed your plugin and have tweaked the CSS so any button after a select will appear in the same style. Try the above, should look like the other button now.

**Comment by davidsherlock** [comment]
Thanks @amdrew, working great now! Actually never knew you could do +`.edd-select ~ .button` in CSS, learn something new every day :)

**Comment by amdrew** [comment]
Hah, awesome!
