### ISSUE TITLE
Checkout quantity field issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#77]
I believe this is actually a core EDD issue, but on the checkout the quantity field looks like this within Themedd:

![screenshot 2017-07-02 21 04 40](https://user-images.githubusercontent.com/22668877/27773132-bf0830dc-5f6a-11e7-9650-ce8141f157a3.png)

It would look better with it's own column (if enabled) and styled to fit better.

**Comment by amdrew** [comment]
I've decreased the width of the quantity field, pull down the latest master @davidsherlock and see how that looks. Moving it to its own column won't be possible.

<img width="803" alt="screenshot 2017-07-03 11 54 13" src="https://user-images.githubusercontent.com/52581/27774454-9b38b9d4-5fe6-11e7-9b56-f7d203475f3d.png">

**Comment by davidsherlock** [comment]
Nice one @amdrew, looks good!
