### ISSUE TITLE
Non-grouped payment history export suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#78]
At the minute the payment history export is grouped by Payment ID, with all the products from the sale included on a per-line basis. I feel however it would be better (and more extensible) to export on a per-item/line basis to allow for more in-depth analysis of sales history, product buying trends, etc outside of EDD.

This would also have the advantage of allowing developers to extend the CSV report, adding maybe FES vendor name, commission amount recorded, etc as additional columns.

**Comment by davidsherlock** [comment]
Sorry @amdrew, this should have been posted in the EDD core repository. Shows how involved I am with Themedd at the minute tho...ha! :)

**Comment by amdrew** [comment]
Hah, no worries!
