### ISSUE TITLE
Menus on fresh install

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#80]
Did a fresh rollout of Themedd and notice some random/test menus were appearing in the customizer:

![screenshot 2017-07-06 22 45 53](https://user-images.githubusercontent.com/22668877/27934351-352bc9d8-629d-11e7-9c8a-52cf99f14f3e.png)

Confused me a bit at first :)

**Comment by amdrew** [comment]
@davidsherlock Those menus didn't come from Themedd. Those are the exact menu names created when you import the Theme unit test data https://codex.wordpress.org/Theme_Unit_Test

**Comment by davidsherlock** [comment]
Apologies @amdrew, must be the lack of sleep! :)

**Comment by amdrew** [comment]
No worries!
