### ISSUE TITLE
Page template hooks required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#82]
Would it be possible to get hooks added to the `full-width.php` and `slim.php` page templates? I'm aware of the hooks in the content-page.php file (within the loop) but I need a before and after outside of the loop if possible to avoid replicating templates when it's not really needed.

**Comment by amdrew** [comment]
@davidsherlock Would you like to see them added before `#main`, or after (inside)? Inside looks to be the best option IMO. 

https://github.com/easydigitaldownloads/themedd/blob/master/page-templates/full-width.php#L13

**Comment by davidsherlock** [comment]
i agree @amdrew, inside in both instances (full-width and slim).

**Comment by amdrew** [comment]
`themedd_main_start` and `themedd_main_end`. Also included these hooks on `page.php`.

**Comment by davidsherlock** [comment]
Cheers Andrew! Will check out later tonight.
