### ISSUE TITLE
Add submenus for color options

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/themedd#83]
Themedd has a lot of color settings (something I love), but all of them are in the same menu and with a random order (header background is in the middle, shopping cart menu is at bottom)

Just a suggestion, use customizer submenus to categorize them (backgrounds, links, text)

**Comment by davidsherlock** [comment]
Agree with @rubengc here, though i think it's better to break the colour options into 'sections' with headings assigned to make it easy to find what you are looking for.

**Comment by amdrew** [comment]
@rubengc I'd love to do that (the current colors do need to be re-ordered) but from what I can see, it's not currently possible to add additional sub-sections via the theme customizer API. Or did you mean move the color options outside of where they are now, and create parent level customizer sections to group them? That is of course possible, however I really like the idea of having a "colors" section so it's very obvious where you need to go to change colors.

**Comment by rubengc** [comment]
Well, I did not played in deep with customizer but i see a lot of plugins with this subsections, for example Email Templates has this feature:
https://wordpress.org/plugins/email-templates/

And Easy Google fonts too:
https://wordpress.org/plugins/easy-google-fonts/

**Comment by amdrew** [comment]
@rubengc Thanks, will check them out

**Comment by amdrew** [comment]
The email templates plugin has essentially created its own customizer. Note how there's 1 base level, and only one level deep

<img width="351" alt="screen shot 2017-07-14 at 6 17 43 pm" src="https://user-images.githubusercontent.com/52581/28235352-f9e88ac6-68c0-11e7-85bd-20d428896e50.png">

<img width="355" alt="screen shot 2017-07-14 at 6 17 49 pm" src="https://user-images.githubusercontent.com/52581/28235353-f9f2e674-68c0-11e7-932d-2eef78d72ef0.png">

**Comment by amdrew** [comment]
I didn't install it, but it looks like the Google Fonts plugin also creates its own settings using the customizer API, since the screenshots don't show it integrated with the default theme customizer. This is not something I think Themedd should do.

**Comment by spencerfinnell** [comment]
@amdrew You can create panels in the customizer. 

Panel > Section > Control(s)

That is what the email plugin does: https://plugins.trac.wordpress.org/browser/email-templates/trunk/includes/class-mailtpl-customizer.php#L52 -- it's using the core Customize API.

**Comment by spencerfinnell** [comment]
And the Google Fonts plugin: https://plugins.trac.wordpress.org/browser/easy-google-fonts/trunk/includes/customizer/class-egf-customize-manager.php#L450

**Comment by amdrew** [comment]
@spencerfinnell Themedd has a "colors" panel already. What we're discussing is another depth of panels. As an example, when you click into the colors custom panel, how do you then click into another panel of grouped colors controls? Any ideas? WordPress does this with menus however as far as I'm aware, it isn't something that's available to take advantage of.

Current:
Customizer -> Colors -> Color controls

What is being requested in this issue
Customizer -> Colors -> Header -> color controls (just for header)

**Comment by amdrew** [comment]
@rubengc As per my question (https://github.com/easydigitaldownloads/themedd/issues/83#issuecomment-315291658), which of the following are you suggesting 

1):

Customizer -> Colors -> Header -> Color controls for header
Customizer -> Colors -> Footer -> Color controls for footer

or 2):

Customizer -> Header -> Color controls for the header
Customizer -> Footer -> Color controls for the footer

**Comment by rubengc** [comment]
The number 1

I suggest It because month ago I was working with the customizer for a need and I remember I was able to do that without custom controls

**Comment by amdrew** [comment]
@rubengc If you remember where you saw that please let me know :) It might be possible with a fair bit of development but I would prefer if it was provided by the core API itself.

**Comment by rubengc** [comment]
I check Themedd customizer, probably the problem comes from add sections to the first level instead of panels as @spencerfinnell mentioned

Check this:
https://wordpress.stackexchange.com/a/175550

**Comment by spencerfinnell** [comment]
Option 1 is definitely possible. 

Panel: Colors
Sections: Header, Footer

Then each section has relevant controls. That is how widgets and menus are done in core. I have a theme customizer library I wrote that I can add you too if you like @amdrew

**Comment by davidsherlock** [comment]
Yeah, I've seen Option 1 done a lot in themes. It's the way to go in my opinion, especially if more options are added in the future.

**Comment by amdrew** [comment]
👍 Will take another look

@spencerfinnell Sure! Would love to check it out

**Comment by amdrew** [comment]
@rubengc Thanks, that link was very helpful and can see how it works now. Will get this implemented soon.

**Comment by amdrew** [comment]
I've categorized all color controls (might change the order) into the following sections:

<img width="348" alt="screen shot 2017-07-19 at 3 26 30 pm" src="https://user-images.githubusercontent.com/52581/28392418-b5bb410c-6c96-11e7-842d-d1aa28d79aa4.png">

Everything is pretty self-explanatory except "general" which contains:

<img width="337" alt="screen shot 2017-07-19 at 3 30 12 pm" src="https://user-images.githubusercontent.com/52581/28392547-3b92b4fe-6c97-11e7-99da-6de90edcfa68.png">

**Comment by amdrew** [comment]
Give that a go ^

**Comment by davidsherlock** [comment]
Looking good @amdrew! Though part of me thinks all the menu stuff should be under a "Navigation" section.

**Comment by amdrew** [comment]
@davidsherlock Happy to consider it for sure. I like how it currently is, grouping color controls by "where" they affect the theme. It seems that most are familiar with "header", "footer" etc. If the customer wants to edit the main navigation, they are probably going to visit the "header" section in the customizer. If they want to change colors of the footer links, they'll go to the "footer" section.

"Navigation" _does_ sound easier but there are many different menus that exist. There's the mobile menu, primary menu, secondary menu, footer menu, plus soon to be social menu. Would all of these color controls exist under the one "Navigation" section? Clicking into the "navigation" section would be pretty long (I admit the header section is currently quite long also) but I feel it would be back to how it was before, a long list of color controls to sift through, not being able to see easily at a glance which color controls are the ones for the footer, which are for the mobile menu etc.

**Comment by amdrew** [comment]
@davidsherlock See https://github.com/easydigitaldownloads/themedd/issues/87

**Comment by davidsherlock** [comment]
Keep it as is at the minute @amdrew, probably safe to close this issue now.

**Comment by davidsherlock** [comment]
@amdrew, just a heads up that I sent you an email with a quick dev question!
