### ISSUE TITLE
Allow customizer color defaults to be overridden

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#87]
The customizer colors defaults should be allowed to be overridden. This would be useful for any child themes or plugins to set a base color scheme, using the existing color controls provided by Themedd.

**Comment by amdrew** [comment]
The above commit adds a `themedd_customize_color_defaults` filter which will allow color defaults to be set.

One important thing to note - if a user has _already_ set a color set via the customizer (thus storing that color in the theme_mods option row) then **no** default color will be set, since it will essentially override the customer’s color they have specified.

**Comment by davidsherlock** [comment]
@amdrew, could you post a quick example of how to properly use this filter? just want to be sure my code is on point (Still learning!).

**Comment by amdrew** [comment]
You could do something like this:

``` php
function themedd_child_default_colors( $defaults ) {

	$defaults['menu_primary_background_color'] = '#000000';

	return $defaults;

}
add_filter( 'themedd_customize_color_defaults', 'themedd_child_default_colors', 10, 1 );
```

I recommend: https://pippinsplugins.com/a-quick-introduction-to-using-filters/

**Comment by davidsherlock** [comment]
Thanks @amdrew, just wanted to be sure I was doing everything right in my child theme!

**Comment by amdrew** [comment]
I think this is good to go.
