### ISSUE TITLE
Logo upload dosen't override site title and description

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#89]
Not sure if this is intentional or not but when upload a logo, the default title and description are still shown below it. I think it would make the most sense to replace those with the logo uploaded. It might also be worth correctly setting the size (or providing a slider) to allow resizing of the logo to fit.

**Comment by amdrew** [comment]
@davidsherlock This was done for flexibility and is also how both the Twenty Sixteen and Twenty Seventeen themes do it, so sticking to what is expected by most users.

There will be instances where a user's logo is not always the "full" logo. It could just be the logo mark. This means a user can upload their logo mark and have their site title below it. Replacing the site title with the logo mark in this scenario wouldn't be a good approach. 

I'm sure they are also many other use-cases. A poor example, but imagine a store selling dog collars. They might like to use a small image of a dog (or a collar) as the "logo", and have their site title next to, or below the image.

If the customer does upload their "full" logo, they can simply hide the site title by unchecking the `Display Site Title and Tagline ` checkbox.

**Comment by davidsherlock** [comment]
Doh! Missed that checkbox :) haha

One thing that "might" be worth adding is the ability to resize your logo using a slider, this is pretty common in themes.

**Comment by davidsherlock** [comment]
Close this one off @amdrew, my error - missed that checkbox!

**Comment by amdrew** [comment]
👍
