### ISSUE TITLE
/vendor page should be full-width

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#93]
The `/vendor/` page should be full-width. Currently it has space on the right because of how single vendor pages (`/vendor/admin/`) have a sidebar.

**Comment by davidsherlock** [comment]
@amdrew, not sure if this is related or not but if full-width mode is enabled, the vendor page dosen't have the body class `layout-full-width` applied.

Is this what you mean here?

**Comment by amdrew** [comment]
This turned into something much bigger than it was supposed to. I ended up creating a new template file just for the single vendor page. For example, `/vendor/admin`. 

Before, whichever page template was applied to the `/vendor` page would also control the single vendor page since they are essentially the same page. If we look at marketplace sites like Etsy, the single vendor page is a very custom page so this is the first step in allowing for some really creative layouts for a single vendor page.

The single vendor page:

- Shows a sidebar by default (as it did before). Because of the presence of a sidebar, the number of download columns has been hard-set to `2`. This means that changing the columns attribute on the vendor page’s [downloads] shortcode will have no effect.
- The single vendor page has its own template called `single-vendor.php`
- The single vendor page has a sidebar template file called `sidebar-single-vendor.php`

**Comment by amdrew** [comment]
@davidsherlock Oops, it is supposed to have that class if full-width has been enabled, will get that fixed.

**Comment by amdrew** [comment]
@davidsherlock Try now with the latest commit.

**Comment by davidsherlock** [comment]
Fixed @amdrew, all good now!

**Comment by amdrew** [comment]
Yeehaw
