### ISSUE TITLE
Duplicate price on download list items

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#95]
Since the last update (which I merged with my parent theme code base), the price displays twice if you have download meta enabled. Think it would be worthwhile to disable the default price and keep  the download meta price since that is easiest style and fit into the design.

Here is a screenshot for illustrative purposes:

![screenshot 2017-08-06 16 29 04](https://user-images.githubusercontent.com/22668877/29004753-082c0a52-7ac5-11e7-962d-8aa2bb3e7f0a.png)

**Comment by amdrew** [comment]
@davidsherlock I had a feeling this morning that the commits from last night would spawn this exact issue 👍 

Pull down the latest commit and give that a test.

**Comment by davidsherlock** [comment]
Weird, was looking into this _literally_ this second...:)

On the same topic, the prices don't seem to appear on the archive pages when enabled via the changes.

**Comment by amdrew** [comment]
Hah! Which archive pages exactly? I'll take a look

**Comment by davidsherlock** [comment]
That commit fixed the double pricing issue, so it's hard to say for sure if it still exists. I have however found another issue which i will create a new thread for.

It was on the taxonomy pages (categories and tags).

**Comment by amdrew** [comment]
Ok cool, let me know if you still see the issue.

**Comment by davidsherlock** [comment]
@amdrew, see issue #97.
