### ISSUE TITLE
Free Downloads button text bug

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#96]
When using the EDD Free downloads add-on, the button text on the list items isn't correct. It should show "Free Download" not "Add to Cart".

On the download list it looks like this:

![screenshot 2017-08-06 16 34 45](https://user-images.githubusercontent.com/22668877/29004764-3f44d05a-7ac5-11e7-972a-ee02d7cbd021.png)

However on the download page it looks like this (correct):

![screenshot 2017-08-06 16 34 50](https://user-images.githubusercontent.com/22668877/29004766-476e48e2-7ac5-11e7-8842-54d4776958f8.png)

**Comment by amdrew** [comment]
Will take a look, thanks!

**Comment by amdrew** [comment]
Can't replicate this, shows `Download Now` on all pages with the [downloads] shortcode, the download archive page and category and tag taxonomy pages. 

@davidsherlock Does your page have the [downloads] shortcode on it? You're testing with Themedd correct (and not your fork)?

**Comment by davidsherlock** [comment]
Andrew, what code (function or template file) is responsible for this button text?

**Comment by amdrew** [comment]
@davidsherlock You'll need to dig into the Free Downloads plugin, Themedd doesn't control anything within Free Downloads.

**Comment by amdrew** [comment]
It does however filter EDD's purchase link defaults, I wonder if that's it.

Can you comment out these lines and see if it fixes it for you? 
https://github.com/easydigitaldownloads/themedd/blob/master/includes/compatibility/edd/filters.php#L50-L52

I still see `Download Now` with the free downloads extension regardless.

**Comment by amdrew** [comment]
It looks like those lines are not required any longer anyway. If I remove them, a free download still says `Add to cart`. I wonder if the text used to be different, and that's why I added it. Hmm.

**Comment by amdrew** [comment]
I see why I added the above code now. 

A default installation of EDD doesn't have any text configured from `Downloads -> Settings -> Misc -> Button Text`. 

<img width="941" alt="screenshot 2017-08-08 17 13 44" src="https://user-images.githubusercontent.com/52581/29057236-f2b6fba2-7c5c-11e7-85e5-889703677d3d.png">

This means that a free download in EDD (not using the Free Downloads extension) will show `Purchase`.

<img width="313" alt="screenshot 2017-08-08 17 14 43" src="https://user-images.githubusercontent.com/52581/29057254-173d168c-7c5d-11e7-939f-edb14686bebe.png">

The code above will change the text to say `Add to Cart` for any free download.

Going back to the actual issue though, when the Free Downloads extension is installed, it should change the button text for a free download in Themedd to `Download Now`. In my testing so far it does do this.

@davidsherlock Try commenting out the lines of code above (and make sure you're using Themedd for testing) to see if that fixes the issue, perhaps it's a priority issue.

**Comment by amdrew** [comment]
Related: https://github.com/easydigitaldownloads/themedd/issues/100

**Comment by davidsherlock** [comment]
Think this one can be safely closed off as well @amdrew!

**Comment by amdrew** [comment]
👍
