### ISSUE TITLE
Download list classes missing from archive and taxonomy pages

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#97]
When the `[downloads]` shortcode is used, Themedd adds some extra classes to the download list container div, however on the archive and taxonomy pages these are all missing.

The classes I mean are as follows:

`has-price has-excerpt has-buy-button has-thumbnails has-download-meta`

I was using these to to style the look of the download boxes.

**Comment by amdrew** [comment]
👍 Will get those added

**Comment by amdrew** [comment]
@davidsherlock Give the above a test. All download grids, whether created by the `[downloads]` shortcode, added via `archive-download.php`, ` taxonomy-download_category.php` or `taxonomy-download_tag.php` will now use the same set of CSS classes.

**Comment by amdrew** [comment]
Just noticed some flawed logic, hold off on testing for now.

**Comment by amdrew** [comment]
Ok that should do it

**Comment by davidsherlock** [comment]
All good now @amdrew! Close this one off.

**Comment by amdrew** [comment]
Sweet!
