### ISSUE TITLE
Download widget "sales" can't be disabled at widget level

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#98]
When using the download details widget on the sidebar, regardless if the "Sales" is checked or not it continues to show when using FES. This appears to be due to the logic in the FES check condition which sets it to true regardless of this option (or at least appears to).

**Comment by amdrew** [comment]
Replicated

**Comment by amdrew** [comment]
@davidsherlock Try that!

**Comment by davidsherlock** [comment]
Fixed @amdrew! Much cleaner code base now as well. Can be closed!

**Comment by amdrew** [comment]
Woot
