### ISSUE TITLE
Disable default button style in EDD settings for theme uniformity

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#99]
I feel this setting should be removed when the theme is active, since it's not something I see people using in the context of this theme design (buttons look _a lot_ better).

**Comment by amdrew** [comment]
@davidsherlock I don't think that option should be removed. Buttons do look better/great but the theme shouldn't remove the decision to use plain text links, it could be something they actually want to do.

**Comment by davidsherlock** [comment]
@amdrew, see what you are saying here - close this one and I will take care of it my version of the theme! :)

**Comment by amdrew** [comment]
👍
